extends RefCounted

# Generated by tools/generate_inventory_outlines.gd; do not edit.
const WIDTH := 2
const INPUT_HASHES := {
	"res://Tiny Swords (Free Pack)/Buildings/Blue Buildings/House1.png": "f68fbce236ca663e2c1d86484f4617586bc99f4f9b634c493e62fa7eeece5c63",
	"res://Tiny Swords (Free Pack)/Buildings/Blue Buildings/House2.png": "21e35d4d47e778c996cc56d95170908f663ca8858f08a6f8637fa15c1236448f",
	"res://Tiny Swords (Free Pack)/Buildings/Blue Buildings/House3.png": "e2be60c4202ceffb55a6d06851ab6b08ffb530867e64da19ae578b09d18097fd",
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png": "ee3f285f992842987df5aae0e07a364a7a535e78d605f6d469115559e87df7e5",
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png": "62de877a4732bee98e170c1a4aac44c3bd39929205923176a4acbec812d2630a",
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png": "e2317a54bb801e52f4c2fbfd4d9d91611036d7b001fe623a92b55539feddaae2",
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png": "ac9094dba8939210726cbcfffec250790081e1eed998edb5e4772ed6bd31d5cc",
	"res://tools/inventory_outline_baker.gd": "0c06e5a520ca054647995568d02345fa3ae3d16a8c024119b7fde9e763585a9c"
}
const TEXTURES := {
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (0, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-0.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (192, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-1.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (384, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-2.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (576, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-3.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (768, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-4.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (960, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-5.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (1152, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-6.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree1.png:[P: (1344, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree-7.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (0, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-0.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (192, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-1.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (384, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-2.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (576, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-3.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (768, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-4.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (960, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-5.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (1152, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-6.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree3.png:[P: (1344, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree2-7.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (0, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-0.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (192, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-1.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (384, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-2.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (576, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-3.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (768, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-4.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (960, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-5.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (1152, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-6.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree2.png:[P: (1344, 0), S: (192, 256)]": preload("res://assets/inventory-outlines/tree3-7.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (0, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-0.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (192, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-1.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (384, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-2.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (576, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-3.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (768, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-4.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (960, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-5.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (1152, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-6.png"),
	"res://Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees/Tree4.png:[P: (1344, 0), S: (192, 192)]": preload("res://assets/inventory-outlines/tree4-7.png"),
	"res://Tiny Swords (Free Pack)/Buildings/Blue Buildings/House1.png:[P: (0, 0), S: (128, 192)]": preload("res://assets/inventory-outlines/house-0.png"),
	"res://Tiny Swords (Free Pack)/Buildings/Blue Buildings/House2.png:[P: (0, 0), S: (128, 192)]": preload("res://assets/inventory-outlines/house-1.png"),
	"res://Tiny Swords (Free Pack)/Buildings/Blue Buildings/House3.png:[P: (0, 0), S: (128, 192)]": preload("res://assets/inventory-outlines/house-2.png")
}
