// Easy-English Chapter 1, preserved from the authored prototype.
export const initial = () => ({ scene: 'opening', first: '', companion: '', arrangement: '', openingReply: '', route: '', items: [], knowledge: [], friendships: [], promises: [], memories: [], journal: [], bram: '', cargo: '', nursery: '', nurseryRole: '', nurseryAction: '', nurseryDetail: '', nurseryDone: false, approach: '', plan: '', goose: '', crossed: false, riskTaken: false, introduction: '', reply: '', sent: false, rest: '', nextRoute: '', outcome: null });
const c = (label, text, next, change = {}, note = '') => ({ label, text, next, change, note });
const page = (step, area, title, text, choices) => ({ step, area, title, text: Array.isArray(text) ? text : [text], choices });
const has = (s, item) => s.items.includes(item);
const knows = (s, fact) => s.knowledge.includes(fact);
const gift = (name) => ({ addItems: [name] });
const learn = (name) => ({ addKnowledge: [name] });
const friend = (name) => ({ addFriendships: [name] });
const present = (s, lines, fallback) => s.companion ? (lines[s.companion] || fallback) : fallback;
const favor = "Next time you visit Reedbank, please tell Sedge I would like to come to the next river party.";
export function transition(s, action) {
  const next = structuredClone(s);
  if (action.type === 'continue') { next.scene = next.outcome.next; next.outcome = null; return next; }
  const choice = action.choice;
  for (const [key, value] of Object.entries(choice.change || {})) {
    if (key.startsWith('add')) { const name = key[3].toLowerCase() + key.slice(4); next[name] = [...new Set([...next[name], ...value])]; }
    else if (key === 'removeItems') next.items = next.items.filter(item => !value.includes(item));
    else next[key] = value;
  }
  if (choice.note) next.journal.push(choice.note);
  if (choice.text) next.outcome = { title: choice.label, text: Array.isArray(choice.text) ? choice.text : [choice.text], next: choice.next };
  else next.scene = choice.next;
  return next;
}
export function story(s) {
  const first = s.first;
  const nearby = s.companion || 'a local animal';
  switch (s.scene) {
  case 'opening': return page(0, 'The pond', 'Seven whole days', [
    "Pip is a little duck. She learned to swim seven days ago.\n“I am very good at swimming!” she thinks.",
    "Today, Mama and Papa take Pip to see the river.",
    "Mama swims under a low branch. Papa puts his head down. Pip puts her head too low. Splash!\nShe comes up with a leaf on her head.",
    "“You look like a little tree!” says Papa.\nPip keeps the leaf on her head."
  ], [c('Swim with Mama and Papa →', '', 'willow')]);
  case 'willow': return page(0, 'The family swim', "The big willow tree", [
    "“We will eat lunch by the big willow tree,” says Mama. “Its long branches hang over the water.”",
    "“Does the tree like to swim?” asks Pip.\n“We can ask it,” says Mama.",
    "Pip swims behind Mama. She moves her tail just like Mama. The river turns ahead.",
    "Pip sees a flower, a round rock, and some bubbles. What does she want to look at?"
  ], [c('Sniff the flower', '', 'meeting', { first: 'Luma' }), c('Climb the warm rock', '', 'meeting', { first: 'Moss' }), c('Follow the bubbles', '', 'meeting', { first: 'Tumble' })]);
  case 'meeting': {
    if (first === 'Luma') return page(0, 'The flower', 'A very large sneeze', ["Something blue is in the flower. Pip puts her nose close.\n“Ah... ah... ACHOO!”", "A blue butterfly falls out. She flaps her wings and flies up.", "“Hello! I’m Luma,” says the butterfly.\n“Were you sleeping?” asks Pip.\n“Yes. Your sneeze woke me up!”"], [
      c('“I’m sorry about the sneeze.”', "“That was a BIG sneeze!” says Luma.\n“I’m Pip,” says Pip.", 'separation', { openingReply: 'Said sorry for the sneeze' }, 'Met Luma in a flower and said sorry for sneezing.'),
      c("“Can you show me how you fly?”", "Luma flies in a little circle.\n“Wow!” says Pip. “I’m Pip. I can swim!”", 'separation', { openingReply: 'Asked about the performance' }, 'Met Luma and asked about her performance.'),
      c('Laugh, then try a bow', "Pip bends her head to say hello. Her beak goes in the water.\n“Hello, water!” says Luma. They both laugh.", 'separation', { openingReply: 'Shared a laugh and a bow' }, 'Met Luma; they made each other laugh.')
    ]);
    if (first === 'Moss') return page(0, 'The warm rock', "That rock has eyes!", ["Pip steps onto the warm rock.\nAn eye opens!\nIt is a turtle!", "“Oh! Hello,” says the turtle.\n“I’m sorry. I thought you were a rock.”\n“I’m Moss. You can climb down now.”"], [
      c("Climb down and say sorry to the rocks too", "Pip says sorry to two rocks too. The rocks say nothing.\nMoss smiles. “Those really are rocks!”", 'separation', { openingReply: 'Said sorry to two ordinary stones' }, 'Met Moss and said sorry to two ordinary stones.'),
      c('“Do you mind being a rock for a little longer?”', "“You can sit for a little while,” says Moss. Pip slides down beside her. A root is stuck under Moss’s shell.", 'separation', { openingReply: 'Asked Moss to stay a rock a little longer' }, 'Met Moss, a surprisingly talkative warm rock.')
    ]);
    return page(0, 'The bubbles', "Bubble hats", ["A frog comes out of the water. A bubble sits on his head.", "“Look at my bubble hat!” he says.\nPop! The bubble is gone.\n“Oh. I need a new hat. I’m Tumble.”"], [
      c('“How do the hats work?”', "“They pop!” says Tumble. “I will try again.”\n“I’m Pip,” says Pip. Tumble makes a smaller bubble.", 'separation', { openingReply: 'Asked how bubble hats work' }, 'Met Tumble and his very temporary bubble hats.'),
      c('“Have you tried a leaf?”', "“A leaf hat! Good idea!” says Tumble. He looks for a leaf. Pip’s leaf falls off her head.", 'separation', { openingReply: 'Suggested a leaf hat' }, 'Met Tumble and suggested a leaf for his hat.'),
      c('Try a bubble hat herself', "Pip stays very still. Pop! Her bubble hat is gone too.\n“That hat was too small,” says Tumble.", 'separation', { openingReply: 'Tried a bubble hat' }, 'Met Tumble and tried an underwater hat.')
    ]);
  }
  case 'separation': return page(0, 'Beyond the bend', "Where are Mama and Papa?", ['Pip turns to show Mama.', "Pip sees the branch.\nShe sees her leaf.\nBut where are Mama and Papa?", '“Mama?”', "She hears a quiet call from the tall grass.\n“Pip?”", "Pip swims toward the call. The water goes two ways through the tall grass.\nShe hears another call. Which way is Mama?", "Pip climbs out of the water. The tall grass keeps the wind away.\nShe feels small. She misses Mama and Papa."], [c('Look up from the safe bank →', '', 'bank')]);
  case 'bank': return page(0, 'The safe bank', "A new friend comes back", [
    ({ Luma: 'Luma lands beside Pip. “Are you looking for the two big ducks?”', Moss: "Moss looks at Pip. “Mama and Papa will be looking for you too.”", Tumble: "Tumble puts his bubble hat down. “Where were you going?”" })[first],
    "“The big willow tree. Mama said we would eat lunch there.”",
    "“I know the first part of the way,” says " + first + ". “But a big goose is in the way.”",
    "“How big?” asks Pip.\nHONK!\nPip jumps.\n“That sounds big!”",
    "“The goose is still far away.”\nPip sits with her new friend. She is safe here."
  ], [c('Begin the journey →', '', 's1')]);
  case 's1': {
    if (first === 'Moss') return page(1, 'The safe bank', 'Someone answers', ["“I need to find Mama and Papa,” says Pip.\n“I will help,” says Moss.", "Moss tries to move. A root is stuck under her shell.\n“But first, can you help me?”"], [
      c("Help push Moss free", "Pip moves a small stick. She gives Moss a little push. The water helps push too. Moss is free!\n“Thank you!” says Moss. “Let’s go together.”", 's2', { companion: 'Moss', arrangement: 'Traveling together', ...friend('Moss — Pip freed her from the root') }, 'Freed Moss by working with the current; she joined Pip.'),
      c("Ask someone to help", "Pip calls a little beetle. They push together. Moss is free!\n“Thank you, both of you,” says Moss. “Let’s go, Pip.”", 's2', { companion: 'Moss', arrangement: 'Traveling together', ...friend('Moss — Pip called for help') }, 'Asked a beetle to help free Moss; she joined Pip.'),
      c("Ask which way to go", "“My home is just ahead,” says Moss. “You can wait there. I can get free.”\nPip finds the path. Moss comes home a little later.", 's2', { arrangement: 'Moss is a contact at home' }, 'Asked Moss for directions and set off by herself.')
    ]);
    if (first === 'Luma') return page(1, 'The safe bank', "A path for Pip", ["“Fly over those bushes,” says Luma.\n“But I can’t fly,” says Pip.\n“Oh!” says Luma. “Let’s find a path.”", "Pip looks under a flower. There is a little gap. She can fit through it."], [
      c("Find a path together", "Pip shows Luma the gap. Luma holds the flower out of the way.\n“A door for ducks!” says Luma. They go together.", 's2', { companion: 'Luma', arrangement: 'Traveling together', ...friend('Luma — found a ground route together') }, 'Helped Luma translate an aerial route into a path for feet.'),
      c("“Fly ahead. I will walk by the water.”", "Luma flies a little way ahead. She comes back to tell Pip what she saw.\n“I will meet you at my flowers,” says Luma.", 's2', { arrangement: 'Luma scouts and returns' }, 'Luma became a returning scout; Pip walks between meeting places.'),
      c("“Show me where to go next.”", "“My flowers are just past that bent flower,” says Luma. She shows Pip the way. Then she goes home.", 's2', { arrangement: 'Luma is a contact at home' }, 'Took Luma’s directions and traveled by herself.')
    ]);
    return page(1, 'The safe bank', 'Ready, almost', ["“Let’s go!” says Tumble.", "But Tumble’s things are all over the ground. He has a smooth seed, some leaves, and two toys he made."], [
      c("Help pick up his things", "Pip holds the leaves while Tumble packs his things.\n“All ready!” says Tumble. They go together.", 's2', { companion: 'Tumble', arrangement: 'Traveling together', ...friend('Tumble — Pip helped meet his belongings') }, 'Gathered Tumble’s scattered belongings; he joined Pip.'),
      c("Ask him to pack less", "“Can you carry all that?” asks Pip. Tumble leaves two toys at home. He keeps his smooth seed.\n“Now I’m ready!” he says.", 's2', { companion: 'Tumble', arrangement: 'Traveling together', ...friend('Tumble — Pip helped make a practical bundle') }, 'Helped Tumble pack lightly; he joined Pip.'),
      c('“Meet me at the next pool.”', "“Wait at my little pool,” says Tumble. He shows Pip the way.\nPip goes there. Tumble comes later with his things.", 's2', { arrangement: 'Tumble is a contact at his pool' }, 'Set off by herself and met Tumble at his home pool.')
    ]);
  }
  case 's2': return page(2, first + '’s home', 'A very small home', [
    ({ Luma: "Luma lives by some flowers.\n“You can sit on this leaf,” she says. Pip tries. The leaf bends.\n“Maybe I’ll sit on the ground!” says Pip.", Moss: "Moss lives by some warm mud. She has little stones and sticks. She likes one round stone best.", Tumble: "“Is this your home?” asks Pip.\n“Yes,” says Tumble. “My toys are here. Well, most of them.”" })[first],
    'There is time for one small thing before leaving.'
  ], [
    c("Look around", "Pip finds a small rope made from grass.\n“You can keep it,” says " + first + ". Pip takes it. She can use it to tie things or pull little things closer.", 's2bye', gift('Small grass rope'), 'Found an unowned reed loop and took it.'),
    c("Ask about the water", first + " drops a leaf into the water. It moves slowly by the edge. In the middle, the water turns round and round. Pip watches.", 's2bye', learn('Quiet water follows the drifting leaves'), 'Learned how floating leaves reveal the quiet edge of a current.'),
    c('Help before leaving', ({ Luma: "Pip holds a flower while Luma fixes her little home.\n“Thank you!” says Luma.", Moss: "Pip helps Moss put her things away. Moss finds her best stone.\n“Here it is!” she says.", Tumble: "Pip holds Tumble’s leaf shelf. He puts his toys on it. They stay up!\n“Thank you,” says Tumble." })[first], 's2bye', friend(first + ' — Pip helped at home'), 'Helped ' + first + ' take care of home.')
  ]);
  case 's2bye': return page(2, first + '’s home', "Come back soon", [({ Luma: "“Come back soon!” says Luma.\n“Can I walk here?” asks Pip.\n“Yes!” says Luma. “I will remember that next time.”", Moss: "“You can visit me any time,” says Moss.", Tumble: "“Goodbye!” calls Tumble. His voice comes back from the far side of the pool.\n“Goodbye!”\nHe laughs and calls again." })[first]], [
    c('“Thank you for letting me visit.”', '', 's3', {}, 'Thanked ' + first + ' for the welcome.'),
    c('“I’ll come back and visit.”', "“Come when you can,” says " + first + ". “I will be happy to see you.”", 's3', { addPromises: ['Visit ' + first + ' at home again'] }, 'Promised to visit ' + first + ' again.'),
    c('“I hope your home doesn’t float away.”', "“Then I’ll tell you where it goes!” says " + first + ". Up ahead, a tiny boat turns round in the water.", 's3', {}, 'Left ' + first + '’s home with a joke.')
  ]);
  case 's3': return page(3, 'A quiet bend', 'The upside down boat', ["A tiny boat is upside down by a root. It is made from the top of an acorn. An acorn is a nut.\nA beetle holds on. His button, string, and little bags float away.", "“Help!” calls the beetle.\n“Are you stuck?” asks Pip.\n“Yes! And very wet!”", 'The water is calm. Pip has time to choose.'], [
    c('Lift Bram onto the bank first', "Pip lifts the beetle onto dry ground. Most of his things float away. His boat hits the root and breaks.\n“I’m Bram,” he says. “Thank you for saving me.”", 's4', { bram: 'Damaged boat', cargo: 'Most things lost', ...friend('Bram — rescued him first') }, 'Saved Bram first. His boat was damaged and most things drifted away.'),
    c("Hold the boat and turn it over", (has(s, 'Small grass rope') ? "Pip catches the side with her little grass rope." : "Pip finds a stick to hold the side.") + " She slowly turns the boat over. Bram climbs in. His boat is fine, but some of his bags float away.\n“You saved me and my boat!” he says.", 's4', { bram: 'Unbroken boat', cargo: 'Some things saved', ...friend('Bram — saved him and his boat') }, 'Saved Bram and saved his boat; only part of his things survived.'),
    c("Ask others to help save Bram", (s.companion ? s.companion + " holds Bram’s things by the edge" : "Some little bugs hold Bram’s things by the edge") + " while Pip helps Bram out. Most of his bags and string are safe. His boat breaks against the root.\n“Thank you, everyone!” says Bram.", 's4', { bram: 'Damaged boat', cargo: 'Most things and string saved', ...friend('Bram — organized a rescue') }, 'Planned Bram’s rescue. Most things survived; the boat needs repair.')
  ]);
  case 's4': return page(4, 'A side stream', 'Across the little stream', ["Pip wants to get to the other side of a little stream.\n“How can I get across?” she asks.", "Pip sees a big root to walk on, a leaf to float on, and a little tunnel under the ground.", present(s, { Luma: s.openingReply === 'Said sorry for the sneeze' ? "“Should I sneeze to say hello?” asks Luma.\nPip laughs. “One sneeze was enough!”" : "“Our next stop!” says Luma. She points to the other side.", Moss: s.openingReply === 'Said sorry to two ordinary stones' ? '“That one really is a rock,” Moss says, before Pip can apologize to it.' : "Moss looks for a safe place to cross.", Tumble: s.openingReply === 'Suggested a leaf hat' ? "“A leaf boat!” says Tumble. “It is bigger than a leaf hat!”" : "“We need a bigger leaf than my hat,” says Tumble." }, "A little bug waves from the other side. Other animals are here too.")], [
    c('Cross with help', present(s, { Moss: "Moss helps Pip swim across the quiet water.", Luma: "Luma shows Pip where the water is not deep. Pip checks each step.", Tumble: "Tumble checks the ground. Then Pip steps across." }, "Pip asks the bug where to walk. It shows her a safe place to cross.") + " Pip feels better with someone to help.", 's5', learn('Crossed the stream with help'), 'Crossed the side stream with help.'),
    c('Make a little leaf raft', knows(s, 'Quiet water follows the drifting leaves') ? "Pip knows where the water is slow. She sits on a big leaf and pushes with a stick. She floats past blue flowers to the other side." : "Pip’s leaf turns round and comes back. She watches another leaf. It moves slowly by the edge.\nPip tries there. This time, she floats past blue flowers to the other side.", 's5', learn('Quiet water follows the drifting leaves'), 'Made a leaf raft and found blue flowers along the quiet edge.'),
    c("Try the little tunnel", "Pip goes into the little tunnel. Oops! She comes out where she started.\nShe tries the other way. Now she is across!", 's5', learn('Low passages follow the bank'), 'Explored the low root passage and found the far bank.')
  ]);
  case 's5': return page(5, 'The raised bank', 'The world gets bigger', ["Pip looks around.\n“The world is so big!” she says. “There is more than my pond!”", "There is a garden on one side. There are pools with big green leaves on the other side.\nFar away, Pip sees little homes. That place is called Reedbank.", "Both paths go to Reedbank. Someone there may know the way to the big river."], [
    c("Take the garden path", "Pip walks into the garden. She sees little homes and a line of busy ants.", 's6', { route: 'Garden bank' }, 'Chose the garden bank route to Reedbank.'),
    c("Swim by the big leaves", "Pip swims into the quiet pools. Big green leaves grow on the water.", 's6', { route: 'Lily pools' }, 'Chose the lily pools route to Reedbank.')
  ]);
  case 's6': {
    if (s.route === 'Garden bank') return page(6, 'The garden bank', "A big bit of bread", ["Some ants push a big bit of bread across the path.", "“Is that your lunch?” asks Pip.\n“Yes!” says an ant. “There is enough for all of us. If we can get it home!”"], [
      c("Hold a leaf bridge for the ants", "Pip holds a leaf like a little bridge. The ants carry their bread across.\n“Thank you!” they say. “We can show you the dry paths.”", 's7', { ...friend('Ants — Pip helped carry Tuesday'), ...learn('Dry garden paths') }, 'Helped the ants move their crumb and earned their friendship.'),
      c("Tell the next ants which path to take", "“Tell the next ants we are taking the high path,” says an ant. Pip says the words again so she will remember.", 's7', { addPromises: ['Tell the next ants: the crumb is coming by the upper path'] }, 'Promised to carry the ants’ route message.'),
      c("Find a gap in the bushes", "Pip walks through a gap in the bushes. She finds an old button in the grass. It is not Bram’s button. No one needs it, so she takes it.", 's7', gift('Shiny button'), 'Found a clearly abandoned garden button at the hedge.')
    ]);
    return page(6, 'The lily pools', "A race above the water", ["Some dragonflies race above the water. They are little bugs with long bodies and wings.", "“What are you doing?” asks Pip.\n“We are racing! Can you help us?”", "Pip watches from the water. She sees things the dragonflies do not see."], [
      c("Pick the race start, then ask the way", "Pip picks a tall plant for the start of the race. Everyone can see it. A dragonfly shows her a quiet way through the water.\n“Thank you for helping!” it says.", 's7', { ...friend('Dragonflies — Pip chose their start marker'), ...learn('Quiet dragonfly channel') }, 'Helped the dragonflies mark their course; learned their quiet channel.'),
      c("Follow the race from the water", "Pip follows the race from the water. The dragonflies teach her a call for boats.\n“Call twice. Then wait.”", 's7', learn('Boat call: two short calls, then a pause'), 'Learned the local boating signal while following the course.'),
      c("Look under the big leaves", "Pip finds a safe way under the big leaves. A little seed shell floats nearby. She takes it. It could help mark a path.", 's7', { ...gift('Seed shell'), ...learn('Sheltered lily passage') }, 'Found a safe lily passage and a loose seed pod.')
    ]);
  }
  case 's7': {
    if (s.route === 'Garden bank') return page(7, 'The message path', 'Nell and the two messages', [
      s.promises.some(p => p.startsWith('Tell the next ants')) ? "Pip finds the next ants. “They are taking the high path!” she says.\n“Thank you!” they say. Pip has kept her promise." : "A snail looks down two paths. Her name is Nell. She carries notes to people.",
      "Nell has two notes. She knows who needs them. But she has forgotten the way to their homes.",
      "“Turn left,” says Nell.\n“Here?” asks Pip.\n“Um... I’m not sure.”",
      "One note says when some food will come. The other asks someone to a party. Pip can help Nell find the homes."
    ], [
      c('Visit the nearer home first', "Pip and Nell go to the nearest home. Someone there shows them the other path. Now Nell can take both notes to the right homes. She offers to write a note to help Pip too.", 'nellNote', { ...friend('Nell — Pip helped find the delivery paths'), promises: s.promises.filter(p => !p.startsWith('Tell the next ants')) }, 'Helped Nell find both delivery routes, starting with the nearer home.'),
      c("Take the food note first", "Pip and Nell take the food note first. The family needs to know when its food will come. Then they find the way to the other home.\n“Thank you,” says Nell. “I can write a note to help you too.”", 'nellNote', { ...friend('Nell — Pip prioritized the urgent delivery'), promises: s.promises.filter(p => !p.startsWith('Tell the next ants')) }, 'Helped Nell deliver the urgent news first; both delivery routes are settled.'),
      c('Ask the ants to guide them', (s.friendships.some(f => f.startsWith('Ants')) ? "“You helped with our bread!” say the ants. “We will show you the way.”" : "Pip carries a small stick for the ants. They show Nell the right paths.") + " Now Nell knows where to take both notes. She offers to write a note to help Pip too.", 'nellNote', { ...friend('Nell — Pip found guides for her deliveries'), promises: s.promises.filter(p => !p.startsWith('Tell the next ants')) }, 'Found ant guides for Nell; both messages can be delivered.')
    ]);
    return page(7, 'An unmarked pool', 'Where did home go?', ["A little beetle looks at three holes under the big leaves.\n“Which one is my home?” he asks.", "“I put a little sign by my door,” he says. “But it floated away!”", "All the holes look the same."], [
      c("Look by the slow water", (knows(s, 'Quiet water follows the drifting leaves') ? "Pip knows where things float in the slow water." : "Pip follows the slow leaves.") + " She finds the beetle’s sign! They tie it by his door.\n“Thank you,” he says. “Here is a call for boats. Call twice, then wait.”", 's8', { addKnowledge: ['Found the beetle’s home marker', 'Boat call: two short calls, then a pause'], ...friend('Water beetle — Pip found his marker') }, 'Found the beetle’s marker and left it at his home; learned the boating signal.'),
      c("Make a new sign for his home", (has(s, 'Seed shell') ? "Pip gives him her seed shell for a new sign." : "Pip folds a leaf into a new sign.") + " The beetle ties it by his door.\n“Now I know my home!” he says. “Let me teach you the boat call. Call twice, then wait.”", 's8', { removeItems: has(s, 'Seed shell') ? ['Seed shell'] : [], ...learn('Boat call: two short calls, then a pause'), ...friend('Water beetle — Pip made a home marker') }, 'Made a replacement marker for the beetle and learned the boating signal.'),
      c('Ask the dragonflies to look from above', "Pip asks the dragonflies to look from the sky. They find the beetle’s home. He puts up a new sign.\n“Thank you,” he says. “Here is the boat call. Call twice, then wait.”", 's8', { ...learn('Boat call: two short calls, then a pause'), ...friend('Water beetle — Pip called for help') }, 'Asked the dragonflies to find the beetle’s home and learned the boating signal.')
    ]);
  }
  case 'nellNote': return page(7, 'The garden message path', 'A name to ask for', ["“Go to the place where boats stop on the big river,” says Nell. “Ask the helper there. Would you like a note from me?”", "“There is an old picnic basket up ahead,” says Nell. “You can stay dry there if it rains.”"], [
    c("Take Nell’s note", "Nell writes, “Pip helped me. Please help her find her way.” Pip keeps the note safe.", 's8', { introduction: 'Nell', ...gift('Nell’s note') }, 'Accepted a written note from Nell.'),
    c("“Thank you. I can tell them who I am.”", "“That is fine,” says Nell. “Tell the helper you came through the garden.”", 's8', {}, 'Declined Nell’s note warmly; kept the directions.')
  ]);
  case 's8': {
    if (s.route === 'Garden bank') return page(8, 'A forgotten picnic basket', 'A very large snore', ["Rain falls on the basket. Something snores under a cloth inside.\nSNOOOORE!\n“That is a big snore!” thinks Pip.", "Someone lives in the basket. Its handle is broken."], [
      c("Say hello", "“Hello?” says Pip. The little animal wakes up.\n“Come in out of the rain!”\nThey talk. Pip learns that people leave useful things for others where the boats stop.", 's8after', learn('River landings have things left for travelers'), 'Shared stories and shelter with the basket’s occupant.'),
      c("Help fix the handle", (has(s, 'Small grass rope') ? "“Can I fix your handle?” asks Pip. She uses her little grass rope to fix it." : "“Can I fix your handle?” asks Pip. She ties grass around the broken part.") + (has(s, 'Shiny button') ? " “You can stay here any time,” says the little animal. “Your button may be useful later.”" : " “Here is a button for you,” says the little animal. “Thank you for helping.” Pip takes it.") , 's8after', { removeItems: has(s, 'Small grass rope') ? ['Small grass rope'] : [], addItems: has(s, 'Shiny button') ? [] : ['Shiny button'], ...friend('Basket animal — Pip repaired the handle') }, 'Repaired the basket with permission; received thanks and an offered gift.'),
      c('Continue along the bank', present(s, { Luma: "Pip and Luma find a dry place. Pip tells her about Papa’s leaf joke. Luma listens.", Moss: "Pip and Moss find a dry place. Pip tells her how Mama moves her tail when she swims. Moss listens.", Tumble: "Pip and Tumble find a dry place. Pip tells him how Papa made her laugh.\n“He sounds kind,” says Tumble." }, "Pip finds a dry place. She thinks of swimming behind Mama. It was fun. She misses her."), 's9', { addMemories: ['Remembered the family swim during the rain'] }, 'Let the basket’s occupant sleep and rested under a dry overhang.')
    ]);
    return page(8, 'The bottle bend', "A frog’s map", ["A bottle is stuck by some roots. There is a drawing inside. A frog sits nearby.", "“That is my map,” says the frog. “You can look.” His house fills most of the page. A line says BIG RIVER.", "“Have you been to the big river?” asks Pip.\n“No,” says the frog. “I guessed that part!”"], [
      c("Get the bottle and look at the map", "Pip takes out the map. One little path is right. The frog guessed the rest.\n“You can keep it,” he says. “I can draw another.”", 's8after', { ...gift('Frog map'), ...learn('The frog’s local bank passage') }, 'Received the frog’s sketch with permission; learned one reliable local passage.'),
      c("Ask which path the frog knows", "The frog shows Pip a path he knows. He tells her where it starts. He keeps his map.", 's8after', { ...learn('The frog’s local bank passage'), ...friend('Mapmaker — Pip took his local knowledge seriously') }, 'Asked the mapmaker about his reliable local passage; left him his map.'),
      c('Leave the bottle and follow the bank', "Pip walks by the quiet water. She finds a path ahead. The frog waves goodbye.", 's9', learn('Observed the onward bank route'), 'Left the bottle in place and found the way by observation.')
    ]);
  }
  case 's8after': return page(8, s.route, 'A little more exploring?', [s.route === 'Garden bank' ? "The little animal wants to make a dry place for other animals to rest. Pip can stay and help, or go to Reedbank." : "The frog wants to check a part of his map. Pip can help, or go to Reedbank."], [c('Continue toward Reedbank', '', 's9'), c("Stay and help a little more", '', 'detour')]);
  case 'detour': return page('Optional', s.route, s.route === 'Garden bank' ? 'Room for the next traveler' : "Check the map", [s.route === 'Garden bank' ? "A neighbor gives them a dry leaf. Pip can help make a little roof. What kind of roof?" : "Pip and the frog look at a little pool. Now they know what is really there. What should they draw on the map?"], s.route === 'Garden bank' ? [
    c("Make a low leaf roof", "Pip puts the leaf close to the ground. A wet ant comes in out of the rain. The little animal will look after this new resting place.", 's9', { addMemories: ['Helped make the basket-bank rain shelter'] }, 'Built a low rain shelter; welcomed its first guest.'),
    c('Leave room for bigger travelers too', "A neighbor gives them a tall stick. They lift the leaf higher. Now a beetle with a big bag can fit too!", 's9', { addMemories: ['Helped build the guest leaf beside the basket'] }, 'Made a taller guest shelter beside the basket.')
  ] : [
    c("Draw the safe path", "Pip checks the way out of the pool. The frog draws it on his map.\n“Now I know the way!” he says. " + (has(s, 'Frog map') ? "He fixes Pip’s map too." : "He keeps his new map at home."), 's9', learn('Tested the mapmaker’s safe inlet passage'), 'Explored the inlet with the mapmaker and marked a safe passage.'),
    c("Draw the good resting place", "They find a place out of the wind. The frog draws a big dot.\n“A good place to rest!” he says.", 's9', { addMemories: ['Marked a quiet resting place with the mapmaker'] }, 'Explored the inlet and marked its quiet resting place.')
  ]);
  case 's9': {
    const callback = s.bram === 'Unbroken boat' ? "Bram comes in his little boat.\n“Hello, Pip! My boat still works. Thank you!”" : s.cargo === 'Most things lost' ? "Bram comes with the few things he saved.\n“You saved me,” he says. “Thank you.” His boat is still being fixed." : "Bram comes with his string. His boat is still being fixed.\n“You and your helpers saved most of my things,” he says. “Thank you!”";
    if (s.route === 'Garden bank') return page(9, 'A wet ditch near Reedbank', "Bram comes back", ["Rain has filled a hole across the path. The ants are fixing a leaf bridge. A dry path goes around the hole too.", callback], [
      c('Ask the ants for help', s.friendships.some(f => f.startsWith('Ants')) ? "“Our friend Pip!” say the ants. They hold the leaf bridge still. Pip walks across." : "Pip holds the bridge while the ants fix it. Then they help her cross.", 's10', {}, 'Crossed the wet ditch with the ants.'),
      ...(s.cargo === 'Most things and string saved' ? [c('Use the string Bram offers', "“You can use my string,” says Bram. Pip holds it as she crosses. Then she gives it back.\n“I know people at Reedbank,” says Bram. “I can help you meet them.”", 's10', {}, 'Borrowed Bram’s rescued string for the ditch and returned it.')] : []),
      c("Take the dry path around", "Pip takes the high path. She can see Reedbank’s little homes. Bram can help her meet people there.", 's10', learn('Dry side route into Reedbank'), 'Found a dry side route to Reedbank.')
    ]);
    return page(9, 'Tangled lilies near Reedbank', "Bram comes back", ["Lots of big leaves block the water ahead.", callback], [
      ...(s.bram === 'Unbroken boat' ? [c("Ask Bram to take a string across", "Bram takes a string through a small gap in his boat. Pip follows it through the quiet water.\n“My boat can help too!” says Bram.", 's10', {}, 'Bram’s saved boat carried a guide line through the lilies.')] : s.cargo === 'Most things and string saved' ? [c("Use Bram’s string", "Bram lends Pip his string. She holds a plant out of the way. Other animals help make a gap. Pip gives the string back.", 's10', {}, 'Used Bram’s surviving string at the lilies, then returned it.')] : []),
      c("Ask the animals here", knows(s, 'Boat call: two short calls, then a pause') ? "Pip calls twice, then waits. A dragonfly hears her. It shows her a gap in the leaves. Bram waves goodbye." : "Pip asks for help. A dragonfly flies up and finds a gap in the leaves.", 's10', {}, 'Asked local creatures to guide her through the lily tangle.'),
      c('Find the quiet edge herself', knows(s, 'Low passages follow the bank') ? "Pip remembers the little tunnel. She looks by the water and finds another way under the roots." : "Pip watches the slow leaves. She follows them around the big plants.", 's10', learn('Quiet edge through the lily tangle'), 'Found her own quiet route past the tangled lilies.')
    ]);
  }
  case 's10': return page(10, 'Reedbank entrance', "Someone knows the way", [s.route === 'Garden bank' ? "Pip reaches Reedbank. Someone is putting bowls on a big table." : "Pip reaches Reedbank by the water. She hears people talking by a big table.", "“Is someone waiting for you?” asks a little animal.\n“Mama and Papa,” says Pip. “But I don’t know where they are.”", "“I’m Sedge,” says a small brown animal. She looks a little like a mouse.\n“Come and eat. You can rest here too.”"], [
    c('Explain the whole morning', "Pip tells Sedge about the leaf, " + first + ", and losing Mama and Papa. Sedge listens.\n“The big willow tree is farther along the big river,” she says. “We can show you where the boats stop.”", 's11', learn('The willow is beyond the marsh, along the main river'), 'Told Sedge the whole morning; learned the direction to the main river.'),
    c("Ask the way to the big river", "Sedge points to a narrow path across the water.\n“A goose is in the way,” she says. “Stay out of the fast water beside him. It flows toward metal bars. You could get stuck.”", 's11', learn('The willow is beyond the marsh, along the main river'), 'Asked for a clear river route and learned about the crossing path.'),
    c('Ask for a quiet place first', "Sedge finds a quiet place for Pip. Pip rests. Then Sedge shows her the way to the big river. The willow tree is farther on.", 's11', learn('The willow is beyond the marsh, along the main river'), 'Rested safely at Reedbank, then received the river directions.')
  ]);
  case 's11': return page(11, 'The shared table', "Come and eat", ['Sedge finds a bowl small enough for Pip.', "“Do you all live here?” asks Pip.\n“Yes,” says Sedge. “We eat together and help each other.”", 'Pip can sit wherever she likes.'], [
    c("Sit with the boat helpers", (s.bram === 'Damaged boat' ? "Pip sees Bram’s broken boat. Some animals are still fixing it." : "Bram’s boat floats by the table. Some of his bags are gone.") + " The animals tell Pip about a safe edge by the goose’s path. Then they talk about a problem. The baby frogs’ pool needs more water.", 's11home', learn('The crossing path has safe edges to inspect'), 'Sat with the repairers; Bram’s boat matched the rescue outcome.'),
    c("Sit with Nell and her friends", (s.friendships.some(f => f.startsWith('Nell')) ? "Nell moves over. “Hello, Pip! Sit with me.”" : "“I’m Nell,” says a snail. “I carry notes.”\n“I’m Pip,” says Pip.") + " Pip learns that boats carry notes up and down the river. Then everyone talks about the baby frogs’ pool. It needs more water.", 's11home', { ...learn('Landings exchange messages'), ...friend('Nell — shared the Reedbank table') }, 'Learned about the river message network at the travelers’ table.'),
    c("Sit with the baby frog helpers", "“A branch fell,” says an animal who looks after the baby frogs. “It blocks the water going to their pool. The babies are safe for now. But we need to help.”", 's11home', learn('A fallen branch diverted the baby frog pool water'), 'Heard about the baby frog pool from its grown-ups.')
  ]);
  case 's11home': return page(11, 'The shared table', 'Something about home', ["Pip sits and eats. Everyone talks softly around her."], [
    c('Describe Mama and Papa', "Pip tells Sedge about Mama’s kind voice and Papa’s funny leaf joke.\n“They sound lovely,” says Sedge. “You can stay here while you need to.”", 's12', { addMemories: ['Described Mama and Papa at the shared table'] }, 'Told the table about Mama and Papa.'),
    c("Tell them about her new friend", "Pip tells them about " + ({ Luma: "waking Luma with a big sneeze", Moss: "saying sorry to Moss because she thought Moss was a rock", Tumble: "Tumble’s bubble hats that kept popping" })[first] + '. ' + (s.companion === first ? first + " tells a little more. Everyone laughs." : "“What happened next?” asks Sedge. Pip smiles and tells her."), 's12', { addMemories: ['Shared the first curiosity at Reedbank'] }, 'Retold her first meeting with ' + first + ' at the table.'),
    c('Listen for a while', "Pip listens to two animals talking about a bowl they share. Then Sedge takes her to see the baby frogs.", 's12', { addMemories: ['Listened quietly at the Reedbank table'] }, 'Listened at the table before visiting the baby frog pool.')
  ]);
  case 's12': return page(12, 'The baby frog pool pool', "The baby frogs need help", ["A branch blocks the water going to the baby frogs’ pool. Grown-ups watch the babies.\nThe babies are called tadpoles. They have tails and no legs yet.", "“Are you a big tadpole?” a baby asks Pip.\n“No. I’m a duck.”\n“Will I be a duck too?”\n“No. You will be a frog!”", present(s, { Moss: "Moss shows Pip where the water used to go.", Luma: "Luma flies over the branch. She tells Pip what she sees.", Tumble: "Tumble checks the edge of the pool." }, "A grown-up shows Pip the blocked water and another pool nearby."), "There are three ways to help. Pip can pick one. Or she can ask the grown-ups to choose."], [
    c("Move the branch out of the way", "“Let’s move the branch,” says Pip. Sedge gets some helpers. The babies wait safely with the grown-ups.", 's13', { nursery: 'Brought back old pool', nurseryRole: 'Helped plan the work' }, 'Chose to restore the old flow; work is not complete yet.'),
    c("Dig a little path for the water", "“Let’s make a little water path around the branch,” says Pip. She and Sedge look for a good place to dig.", 's13', { nursery: 'New channel', nurseryRole: 'Helped plan the work' }, 'Chose to open a controlled new channel; work is not complete yet.'),
    c("Move the babies to the other pool", "The other pool is safe. They need to get it ready. " + (s.bram === 'Unbroken boat' ? "Bram says they can use his boat to move the babies." : "Some animals bring leaf cups to carry the babies. Bram’s boat is still being fixed."), 's13', { nursery: 'Moved baby frog pool', nurseryRole: 'Helped plan the work' }, 'Chose a new baby frog pool pool; the move is not complete yet.'),
    c("Ask the grown-ups to choose", "Sedge asks the grown-ups. “Let’s move the babies to the other pool,” they say. They know it is safe. Pip can help with a small job.", 's13', { nursery: 'Moved baby frog pool', nurseryRole: 'Supported a animal-led plan' }, 'Asked experienced animals to lead the baby frog pool move.')
  ]);
  case 's13': {
    const help = present(s, { Luma: "Luma flies up. She tells the helpers where to go.", Moss: "Moss holds the side still.", Tumble: "“Ready?” asks Pip.\n“Let me check first,” says Tumble." }, "Sedge helps everyone work together.");
    if (s.nursery === 'Brought back old pool') return page(13, 'Beside the fallen branch', "Time to help", ["The helpers stand by the branch. " + (s.friendships.some(f => f.startsWith('Ants')) ? "The ants Pip helped come to move the little sticks." : "The helpers bring their tools."), help], [
      c("Show the helpers which way to lift", "Pip watches the end of the branch.\n“This way!” she calls. The helpers lift together. They roll the branch onto dry ground. Water goes back to the pool!", 's14', { nurseryAction: 'Guided a team lift' }, 'Guided the animals as they moved the branch.'),
      c("Use a grass rope to turn the branch", "The helpers bring a grass rope. They tie it around the branch. They pull, and the water helps turn it. Water goes back to the pool! Pip gives the rope back.", 's14', { nurseryAction: 'Helped turn the branch with a borrowed line' }, 'Used and returned a borrowed grass rope to turn the branch.'),
      c("Move the small sticks first", "Pip moves the little sticks. The helpers try to lift the branch. It slips back down. They try again. It moves! Water goes to the pool.", 's14', { nurseryAction: 'Cleared small sticks' }, 'Cleared small sticks while the team moved the branch.')
    ]);
    if (s.nursery === 'New channel') return page(13, "The new water path would go near someone’s bed.\n“We must keep the bed dry,” says Pip.", "Keep the bed dry", ["The new water path would go near someone’s bed.\n“We must keep the bed dry,” says Pip.", help], [
      c("Ask the animal who sleeps here", "Pip asks the animal who sleeps there. It shows her a better path. The helpers dig slowly. Water reaches the babies’ pool. The bed stays dry.", 's14', { nurseryAction: 'Asked the neighbor and changed the channel line' }, 'Asked the neighboring animal before opening the channel.'),
      c("Dig a longer path around the bed", "The helpers dig a longer path around the bed. It takes more work, but the bed stays dry. Water reaches the pool.", 's14', { nurseryAction: 'Routed the channel around the resting place' }, 'Kept the resting place dry with a longer channel.'),
      c("Plan the water path together", "Pip and the animal plan a bend in the water path. The helpers dig it. Water turns the corner! The bed stays dry.", 's14', { nurseryAction: 'Designed the Little Elbow with its neighbor' }, 'Designed the Little Elbow channel together with the neighbor.')
    ]);
    return page(13, 'Between the baby frog pool pools', 'A careful little move', [s.bram === 'Unbroken boat' ? "Bram’s boat is ready to carry the babies. The water between the pools is calm." : "The helpers make cups from big leaves. Bram helps on dry ground. His boat is still being fixed.", help, "The grown-ups count the babies and stay with them. How will Pip help?"], [
      c('Make many small trips', "Pip goes with the babies on each little trip.\n“Did you always have feet?” a baby asks.\n“Yes!” says Pip. Soon, all the babies are safe in the new pool.", 's14', { nurseryAction: 'Went with many small trips' }, 'Helped make small, calm trips to the new baby frog pool.'),
      c("Help everyone stand in a line", "Pip helps everyone stand in a line. They pass the cups carefully. The grown-ups watch each baby. All the babies arrive safely. Everyone gives the cups back.", 's14', { nurseryAction: 'Organized a line of helpers' }, 'Helped organize the baby frog pool move and return borrowed equipment.'),
      c('Prepare the new pool first', "Pip clears the path to the new pool. A grown-up helps check it. The pool is ready. Soon, all the babies are safe inside.", 's14', { nurseryAction: 'Prepared the new pool' }, 'Prepared the destination while experienced animals led the trips.')
    ]);
  }
  case 's14': return page(14, 'The baby frog pool', "Pip helped!", [({ 'Brought back old pool': "The old pool fills with water again. The branch is out of the way. Animals can sit on it now.", 'New channel': "Water flows along the new little path into the pool. The animals stop to watch.", 'Moved baby frog pool': "The babies swim in their new pool. Other little animals can use the old pool." })[s.nursery], "Sedge smiles at Pip. “You helped!” Pip " + s.nurseryAction.toLowerCase() + ". Now she can do one more little thing."], [
    c("Make a place to sit together", "Pip helps make a leaf roof by the pool. Friends can sit under it together. Sedge saves a place for Pip.", 's14after', { nurseryDone: true, nurseryDetail: 'A leaf roof for party', ...friend('Reedbank — Pip helped its baby frog pool') }, 'Finished the baby frog pool project and made a party place.'),
    c("Put signs on the safe path", "Pip puts little signs along the safe path. A tiny animal follows them to the pool. Sedge smiles.", 's14after', { nurseryDone: true, nurseryDetail: 'A marked safe route', ...friend('Reedbank — Pip helped its baby frog pool') }, 'Finished the baby frog pool project and marked a safe route.'),
    c('Spend time with the tadpoles', "“Will you stay?” asks a baby frog.\n“I need to find Mama and Papa.”\n“Can you come back?”\n“Yes,” says Pip. “I will tell you about the river.”", 's14after', { nurseryDone: true, nurseryDetail: 'Tadpoles waiting for Pip’s river stories', addPromises: ['Tell the tadpoles about the river on a future visit'], ...friend('Reedbank — Pip helped its baby frog pool') }, 'Finished the baby frog pool project and promised the tadpoles a river story.')
  ]);
  case 's14after': return page(14, 'Reedbank', "The path to the river", ["Pip sees the path out of Reedbank. She can come back here to rest any time."], [c('Get ready to leave', '', 's15'), c("Stay for a little party", '', 'evening')]);
  case 'evening': return page('Optional', 'Beside the baby frog pool', 'A little evening', ["Some friends sit by the babies’ pool. It is a small party!"], [
    c('Tell the story of the acorn boat', "Pip tells the babies how she helped Bram.\n“Was his boat THIS big?” asks a baby.\n“No!” laughs Pip. “It was very small!”", 's15', { addMemories: ['Told the acorn-boat story at the baby frog pool evening'] }, 'Shared Bram’s rescue story at the baby frog pool evening.'),
    c("Make shadows on a leaf", "Pip makes a shadow on a leaf. It looks like a huge duck.\n“Will you grow that big?” asks a baby.\n“I don’t think so!” says Pip.", 's15', { addMemories: ['Made duck shadows on a leaf screen'] }, 'Made shadows with the tadpoles at the evening party.'),
    c("Listen to the babies name things", "The babies give a stone four different names. Pip listens. Soon, everyone is sleepy.", 's15', { addMemories: ['Heard the tadpoles give one stone four names'] }, 'Listened to the tadpoles name their new surroundings.')
  ]);
  case 's15': return page(15, 'Reedbank departure', 'Something for the journey', ["The animals offer Pip one gift for her trip. They will still be her friends if she does not take a gift.", "“The goose likes shiny things,” says Sedge. “He may let you pass for a gift. But that path belongs to everyone.”", "“Is it his river?” asks Pip.\n“No,” says Sedge. “He just likes to be the boss.”"], [
    ...(!has(s, 'Grass rope') ? [c("Take a grass rope", "“This grass rope is yours to keep,” says Sedge. Pip rolls it up.", 'departure', gift('Grass rope'), 'Accepted a reed string as a gift from Reedbank.')] : []),
    ...(!has(s, 'Shiny button') ? [c("Take a shiny button", "“You can give this shiny button to someone if it helps,” says Sedge. “It is yours now.”", 'departure', gift('Shiny button'), 'Accepted a polished button as a gift from Reedbank.')] : []),
    ...(!s.introduction ? [c("Take a note from Sedge", "Sedge writes a note. It says Pip helped the baby frogs and is a friend of Reedbank.", 'departure', { introduction: 'Sedge at Reedbank', ...gift('Reedbank note') }, 'Accepted Sedge’s written note.')] : []),
    c("Say “No, thank you”", "“That is fine,” says Sedge. “We are still your friends.”", 'departure', {}, 'Declined a departure gift; Reedbank’s friendship remains.')
  ]);
  case 'departure': return page(15, "The path to the river", 'Who goes with Pip?', [s.companion ? s.companion + " can keep going with Pip. Someone from Reedbank can help too." : s.arrangement === 'Luma scouts and returns' ? "Luma comes back. Pip tells her what happened. Luma can go with Pip now." : first + " is at home. Sedge offers to send someone who knows the way.", "“Stay out of the fast water,” says Sedge. “It flows into metal bars. You could get stuck. Check the quiet edges for a safe way.”"], [
    ...(s.companion || s.arrangement === 'Luma scouts and returns' ? [c('Continue with ' + (s.companion || 'Luma'), (s.companion || 'Luma') + " says goodbye by " + s.nurseryDetail.toLowerCase() + ". Pip looks back, then takes the path to the river. HONK! The goose is ahead.", 's16', { companion: s.companion || 'Luma', arrangement: 'Traveling together' }, 'Left Reedbank with ' + (s.companion || 'Luma') + '.')] : []),
    c("Ask someone here to come along", (s.companion ? s.companion + " stays at Reedbank to help. They say goodbye. " : '') + "Someone from Reedbank walks with Pip and shows her the safe places.", 's16', { companion: 'Reedbank guide', arrangement: 'A local guide accompanies Pip', addMemories: s.companion ? [s.companion + ' stayed at Reedbank to help'] : [] }, 'Left Reedbank with a local crossing guide.'),
    c("Go by herself", (s.companion ? s.companion + " stays at Reedbank to help. Pip can send a note later. " : '') + "Pip says goodbye to the babies and takes the path. She sees a big sign ahead.", 's16', { companion: '', arrangement: 'Traveling by herself', addMemories: s.companion ? [s.companion + ' stayed at Reedbank; Pip can send word'] : [] }, 'Left Reedbank by herself with a warm farewell.')
  ]);
  case 's16': return page(16, 'The goose crossing path', 'The goose crossing', ["A big goose stands on a narrow path across the water. A huge sign is beside him.", 'CROSSING RULES\n1. ASK THE GOOSE.\n2. THE GOOSE IS BUSY.\n3. BE QUIET.', "The goose looks down at Pip.\n“You are very small.”\n“I’m bigger than I was yesterday!” says Pip.", "Other little animals wait to cross too. Fast water runs under the path. Pip can look for another way by the quiet edge."], [
    c("Offer something to the goose", "“Give me something shiny, or help me,” says the goose.\n“How?” asks Pip.\n“You could give me a button. Or take a message to Sedge next time you visit Reedbank.”\nPip has not said yes yet.", 's17', { approach: 'Deal' }, 'Asked the goose for the exact terms of a deal.'),
    c("Ask why he can keep everyone out", (s.companion === 'Moss' ? "Moss says, “I used this path before your sign was here.”" : s.introduction ? "“Sedge said this path was for everyone,” says Pip." : "“We used to share this path,” says an animal.") + " “Well... let’s talk about that,” says the goose. Pip waits for him to explain.", 's17', { approach: 'Shared passage' }, 'Questioned the goose’s ownership of the shared crossing.'),
    c('Ask ' + (s.companion || 'a waiting traveler') + ' for ideas', present(s, { Luma: "“He likes looking at himself in the water,” says Luma. “I can talk to him while you take the safe path.”", Moss: "“Let’s ask why he changed the rules,” says Moss. “This path was for everyone.”", Tumble: "Tumble sees a little tunnel. “Let’s check it first,” he says. “We must stay out of the fast water.”" }, "“I can help you check the quiet path,” says the animal. “Stay out of the fast water.”") , 's17', { approach: s.companion === 'Moss' ? 'Shared passage' : 'Quiet route' }, 'Asked ' + nearby + ' for a crossing plan.'),
    c("Look for another way across", "Pip walks on dry ground. She sees a little path under the roots. She can check it without going into the fast water.", 's17', { approach: 'Quiet route', ...learn('Sheltered edge beside the crossing path') }, 'Scouted a quiet alternative and saw the dangerous metal bars.')
  ]);
  case 's17': {
    const choices = [];
    if (s.approach === 'Deal') {
      if (has(s, 'Shiny button')) choices.push(c("Show the goose the button", "The goose looks at the button. Then he looks again.\n“I like it,” he says. “Give it to me, and you can cross.” Pip still has the button. She can choose.", 's18', { plan: 'Button trade' }, 'Prepared a button trade; the button is still Pip’s.'));
      choices.push(c("Ask what help the goose wants", "“Here is what I want,” says the goose. “" + favor + "” Pip does not have to go back now. She can say yes or pick another way.", 's18', { plan: 'Specific favor' }, 'Heard the goose’s planned favor before agreeing.'));
      choices.push(c("Keep her things and look for a quiet path", "“I will find another way,” says Pip. She goes back to the quiet edge. She has given nothing and promised nothing.", 's17', { approach: 'Quiet route', plan: '' }, 'Withdrew from bargaining without a debt or trip.'));
    } else if (s.approach === 'Shared passage') {
      choices.push(c("Find someone who used this path before", (s.companion === 'Moss' ? "Moss says this path used to be for everyone." : "An older animal says this path used to be for everyone.") + " “Can we all use it again?” asks Pip.", 's18', { plan: 'Shared passage — respectful witness' }, 'Prepared a witness to the old shared plan.'));
      choices.push(c("Ask everyone to speak together", "The waiting animals stand together.\n“Everyone could cross yesterday,” says Pip. “Why can’t we cross today?”\nThe goose looks at them.", 's18', { plan: 'Shared passage — public challenge' }, 'Gathered the waiting travelers to challenge the new rule.'));
      choices.push(c("Look for a quiet path instead", "Pip leaves the sign. She looks for a safe path by the quiet water.", 's17', { approach: 'Quiet route', plan: '' }, 'Changed from public discussion to scouting a quiet route.'));
    } else {
      choices.push(c("Check the ground by the quiet water", (knows(s, 'Quiet water follows the drifting leaves') ? "Pip sees leaves floating slowly by the edge. She knows the water is quiet there. " : "Pip watches the leaves. They move slowly by the edge. ") + present(s, { Moss: "Moss checks the ground by the quiet water.", Tumble: "Tumble checks each step to make sure it is safe.", Luma: "Luma flies a little way ahead. She comes back to tell Pip what she sees." }, "An animal helps check the ground.") + " They find a safe path around the goose.", 's18', { plan: 'Quiet safe edge' }, 'Checked a safe route instead of entering the open current.'));
      choices.push(c("Check the little tunnel", (knows(s, 'Low passages follow the bank') ? "Pip finds a little tunnel like the one she used before." : "Pip checks where the tunnel ends. An animal shows her the other end.") + " The tunnel is above the fast water. It goes to the other side.", 's18', { plan: 'Quiet root passage' }, 'Verified the low root passage before using it.'));
      if (s.companion === 'Luma') choices.push(c("Let Luma talk to him while Pip walks around", "“Look at yourself in the water!” Luma tells the goose. “Which side looks best?”\nWhile he looks, Pip checks the quiet path. Luma will meet her on the other side.", 's18', { plan: 'Luma’s distraction' }, 'Prepared Luma’s distraction and a checked safe route.'));
    }
    if (!s.riskTaken) choices.push({ ...c("Look at the fast water…", '', 'warning'), risk: true });
    return page(17, 'The banks beside the crossing path', s.riskTaken ? 'A safer plan' : 'A plan or a shortcut', [s.riskTaken ? "Pip is safe. She has all her things back. She is still on the same side. Now she can find a safe way across." : "Pip can get ready for her plan. The fast water goes straight to the metal bars. It is too strong for her.", "Pip’s plan: " + s.approach.toLowerCase() + '.'], choices);
  }
  case 'warning': return page(17, 'The fast channel', 'The current is too strong', ["Pip sees metal bars across the fast water. Sticks are stuck there. She could get stuck too.", present(s, { Tumble: "“That water is too fast,” says Tumble. “Let’s find a safe way.”", Moss: "“I can’t carry you through that water,” says Moss.", Luma: '“I can fly over it,” says Luma, “but I cannot carry you.”' }, "“Even big swimmers stay out of there,” says an animal."), "If Pip goes into the fast water, it will pull her away. Someone will have to help her out. You can choose a safer way."], [
    c('Choose another way', '', 's17'),
    { ...c('Take the risk', "The fast water pulls Pip toward the metal bars. She grabs a root. An animal on dry ground helps her out.\nPip is safe. But she is still on the same side. Her things are all along the edge.", 'recovery', { riskTaken: true, suppliesScattered: true, plan: '' }, 'Tried the warned current; was rescued safely to the near bank.'), risk: true }
  ]);
  case 'recovery': return page(17, 'A safe ledge on the near bank', 'A moment to recover', ["Pip rests. The animals pick up her things for her.", "“Take your time,” they say. “We can try a safe way when you are ready.”", "Pip can rest as long as she needs. She will not try the fast water again."], [c("Rest, then choose a safe way →", "Pip has all her things back. She returns to the quiet edge to choose a safe way.", 's17', { suppliesScattered: false }, 'Found all things and returned to the same crossing preparation.')]);
  case 's18': {
    if (s.plan === 'Button trade') return page(18, 'The crossing path', "A button to cross", ["The goose will let Pip cross if she gives him her button. She still has it. Does she want to give it to him?"], [
      c("Give him the button and cross", "The goose takes the button and moves aside.\n“It is quite shiny,” he says. Pip walks across. He does what he promised.", 'crossingOthers', { removeItems: ['Shiny button'], crossed: true, goose: 'Kept an object deal' }, 'Traded her garden button once and crossed by agreement.'),
      c('Keep the button and choose another plan', '', 's17', { plan: '' })
    ]);
    if (s.plan === 'Specific favor') return page(18, 'The crossing path', "One small promise", ["The goose says what he wants again:", favor, "Pip can promise to do this. Or she can choose another way."], [
      c("Promise to help, then cross", "Pip says the promise again.\n“Yes. Just that,” says the goose. He lets her cross. Pip can carry his message the next time she visits Reedbank.", 'crossingOthers', { addPromises: [favor], crossed: true, goose: 'Kept a deal for a specific future favor' }, 'Agreed to the exact message-carrying favor and crossed.'),
      c("Say no and choose another way", '', 's17', { approach: 'Quiet route', plan: '' })
    ]);
    if (s.plan.startsWith('Shared passage')) return page(18, 'The shared crossing path', "Everyone can cross", ["“This path was for everyone,” says Pip. The other animals say she is right.", s.plan.includes('respectful') ? "Pip waits for the goose to answer. He looks at the animals, then at his sign." : "“Why did you change it?” asks Pip. Everyone waits for an answer.", "“I have a new rule!” says the goose. “Everyone can cross!”"], [c("Cross with everyone", "Pip and the other animals cross. The goose changes his sign. He will remember Pip asking him to share the path.", 'crossingOthers', { crossed: true, goose: s.plan.includes('respectful') ? 'Grudging respect; shared passage brought back' : 'Considers Pip troublesome; shared passage brought back' }, 'Brought back shared passage with the waiting travelers and crossed.')]);
    return page(18, 'The safe way around', 'Getting across', [(s.plan === 'Luma’s distraction' ? "Luma talks to the goose about how he looks in the water. Pip takes the safe path. Luma flies over to join her." : s.plan === 'Quiet root passage' ? "Pip goes through the tunnel she checked. The ground is firm. The tunnel takes her to the other side." : "Pip follows the safe path. She checks each step.") + (s.riskTaken ? " This time, she stays out of the fast water." : ''), "Pip is across! The goose has not seen her."], [
      c("Go before the goose sees her", "Pip walks behind the tall grass. The goose keeps looking at his sign.", 'crossingOthers', { crossed: true, goose: 'Unaware of Pip’s quiet crossing' }, 'Crossed safely by the quiet route and left unnoticed.'),
      c("Call to the goose from the other side", "“You went around me!” calls the goose.\n“Yes,” says Pip. “I found a safe path.”\nThe goose looks at his sign.", 'crossingOthers', { crossed: true, goose: 'Noticed and remembers Pip’s going around him' }, 'Crossed safely and acknowledged the goose; he remembers the going around him.')
    ]);
  }
  case 'crossingOthers': return page(18, 'The far bank', 'Someone still waiting', ["A small animal on the other side calls to Pip.\n“Is that way safe?”\nPip can hear the big river ahead."], [
    c("Explain the safe way", "Pip explains the safe path. “Stay out of the fast water,” she says. " + (s.plan.startsWith('Shared') ? "The path is open to everyone now." : s.plan.includes('Quiet') || s.plan === 'Luma’s distraction' ? "The animal checks the quiet path before using it." : "“The goose let me pass because I gave him something,” says Pip. “You will need to ask him. Or check the quiet path.”"), 's19', { addMemories: ['Explained the crossing to another traveler'] }, 'Passed on accurate crossing information to the waiting traveler.'),
    c("Ask the goose to let others cross too", s.plan.startsWith('Shared') ? "“Everyone can cross now,” says the goose. The animals cross. Pip thanks the animal who helped her speak to him." : "“This one can cross,” says the goose. One small animal comes across. He has not said yes to everyone.", 's19', { addMemories: ['Asked for passage for another traveler'] }, 'Asked the goose to let waiting travelers cross.'),
    ...(s.companion ? [c('Continue while ' + s.companion + ' explains', s.companion + " stays to show the animal the way. Pip waits by the big river. Her friend soon joins her.", 's19', { addMemories: [s.companion + ' passed on the crossing information'] }, 'Let her companion explain the crossing, then reunited at the river.')] : [])
  ]);
  case 's19': return page(19, 'The main river', "The big river", ["The river is very big.\nPip looks at the wide water. Then she sees a small place where boats stop.\n“I can go there,” she thinks.", "There are steps and a little roof. An animal is fixing a sign for the boats.", present(s, { Luma: "“Wow,” says Luma softly.", Moss: "Moss shows Pip the quiet water by the steps.", Tumble: "“Let’s check the path first,” says Tumble." }, "Pip watches a leaf float down the river. Then she looks at the little roof. It looks warm and dry.")], [
    c("Help call to a boat", knows(s, 'Boat call: two short calls, then a pause') ? "Pip calls twice, then waits. A boat answers!\n“You know the boat call,” says the helper. “Come and rest.”" : "Pip holds the sign while the animal fixes it. Then she calls to a boat.\n“Thank you,” says the helper. “Come and rest.”", 'landingName', {}, 'Reached the boat stop by helping signal a boat.'),
    c('Follow the bank to the steps', (knows(s, 'Low passages follow the bank') ? "Pip sees a little path by the water. It looks like one she used before. " : "Little signs show Pip the path to the steps. ") + "She reaches the steps by herself. The helper makes room for her under the roof.", 'landingName', {}, 'Reached the boat stop by herself along the bank.'),
    c(s.introduction ? 'Use ' + s.introduction + "’s note" : 'Explain that Reedbank sent her', (s.introduction ? "The helper reads the note. “" + (s.introduction === 'Nell' ? "I know Nell. She is kind." : "Sedge! I know her.") + '”' : "Pip tells the helper about Sedge and the baby frogs.\n“You met my friends!” says the helper.") + " “Come in, Pip. You can rest here.”", 'landingName', {}, 'Arrived using ' + (s.introduction ? s.introduction + '’s actual note.' : 'a truthful description of Reedbank.'))
  ]);
  case 'landingName': return page(19, 'The boat stop roof', 'A place to ask', ["“Boats carry notes between places like this,” says the helper. “I know the big willow tree. It is farther along the river.”", '“And what is your name?”'], [c('“Pip.”', "The helper stops and looks at Pip.", 's20', {}, 'Gave her name at the river boat stop.')]);
  case 's20': return page(20, 'The boat stop roof', 'Something left for Pip', ["“Pip?” says the helper.\n“I have a note for you!”", "A boat brought a note from Mama and Papa."], [
    c('Read it quietly', '', 'letter', { reading: 'Read the note quietly' }),
    c('Ask ' + (s.companion || 'the helper') + ' to stay beside her', '', 'letter', { reading: 'Read with ' + (s.companion || 'the helper') + ' beside her' }),
    c('Read the note aloud', '', 'letter', { reading: 'Read the note aloud' })
  ]);
  case 'letter': return page(20, 'The boat stop roof', 'Mama and Papa', [
    "Pip,\n\nWe are looking for you.\n\nAsk a kind helper where the boats stop. We are sending notes along the river.\n\nWe love you.\n\nMama and Papa",
    s.reading === 'Read the note aloud' ? "Pip reads the words out loud. Everyone listens." : s.reading === 'Read the note quietly' ? "Pip reads the note quietly. Then she reads it again. The helper waits." : (s.companion || 'The helper') + " stays with Pip as she reads. She can take her time.",
    "“Can I send them a note?” asks Pip.\n“Yes,” says the helper. “The next boat can take it.”"
  ], [c('Choose what to tell them →', '', 'reply')]);
  case 'reply': {
    const safety = s.companion ? 'I’m safe. I made a friend.' : 'I’m safe. Some kind people helped me.';
    return page(20, 'The boat stop message table', 'What should the message say?', ["The helper gets some paper. A boat stops by the steps."], [safety, 'I miss you. I’m trying to find you.', 'I helped some tadpoles. I’ll tell you everything.'].map(reply => c('“' + reply + '”', '', 'confirmReply', { reply })));
  }
  case 'confirmReply': return page(20, 'The boat stop message table', 'One small message', ["The helper reads Pip’s words back to her:", '“' + s.reply + '”', 'Pip can still change them.'], [
    c('Send this message', "The helper gives Pip’s note to the next boat.\nPip watches it leave.\n“My words are going to Mama and Papa,” she thinks.", 'rest', { sent: true }, 'Sent to Mama and Papa: “' + s.reply + '”'),
    c('Change the message', '', 'reply')
  ]);
  case 'rest': return page(20, 'Beside the boat stop', 'A warm place to sleep', ["Pip has a warm place to sleep. Mama and Papa are looking for her. A boat is taking her note to them.", 'Tonight she is safe. Where would she like to rest?'], [
    ...(s.companion ? [c('Near ' + s.companion, s.companion + " lies down near Pip. She feels better with a friend close by.", 'nextRoute', { rest: 'Near ' + s.companion }, 'Chose to sleep near ' + s.companion + '.')] : []),
    c("Near the boats and the helper", "Pip hears the boats move softly. The helper is nearby. She feels safe and closes her eyes.", 'nextRoute', { rest: 'Near the sounds of the boat stop' }, 'Chose a sleeping place near the sounds of the boat stop.'),
    c('In a quiet corner', "The corner is warm. The wind cannot reach Pip here. She curls up and rests.", 'nextRoute', { rest: 'A quiet corner' }, 'Chose a quiet corner to sleep in.')
  ]);
  case 'nextRoute': return page(20, 'The river boat stop', 'When morning comes', ["The big willow tree is still far away.\n“Tomorrow, you could walk through the river gardens,” says the helper. “Or you could take a boat that stops along the river.”", "What would Pip like to try? She can learn more in the morning."], [
    c("Pip would like to walk through the gardens", '', 'ending', { nextRoute: 'Bank path through river gardens' }, 'Preferred the river garden path for Chapter 2.'),
    c('Pip would like to try the local boat', '', 'ending', { nextRoute: 'Local boat with several stops' }, 'Preferred a local boat journey for Chapter 2.')
  ]);
  case 'ending': return page(20, 'Safe at the main river boat stop', "Safe for tonight", ["Pip has come a long way. She has helped new friends. Now a boat carries her note:", '“' + s.reply + '”', "Mama and Papa are still looking for Pip. She has not found the big willow tree yet. But tonight she is safe and warm.", "End of Chapter 1.\nThat is all of Pip’s story for now."], [c("Read Pip’s notebook", '', 'ending', { notebook: true })]);
  }
}
