extends SceneTree

const Baker = preload("res://tools/inventory_outline_baker.gd")
const DIRECTORY := "res://assets/inventory-outlines"

func _initialize() -> void:
	if DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(DIRECTORY)) != OK:
		push_error("Cannot create inventory outline asset directory")
		quit(1)
		return
	var entries: Array[String] = []
	var hashes := {"res://tools/inventory_outline_baker.gd": FileAccess.get_sha256("res://tools/inventory_outline_baker.gd")}
	for entry in Baker.inputs():
		var texture: Texture2D = entry.texture
		var region: Rect2i = entry.region
		var destination: String = DIRECTORY.path_join(entry.name + ".png")
		var image: Image = Baker.texture_for(texture, region).get_image()
		if image.save_png(ProjectSettings.globalize_path(destination)) != OK:
			push_error("Cannot save inventory outline: " + destination)
			quit(1)
			return
		# Godot's default alpha-border correction changes transparent RGB
		# pixels. Keep the imported texture identical to the old ImageTexture.
		var settings := ConfigFile.new()
		if FileAccess.file_exists(destination + ".import"):
			settings.load(destination + ".import")
		settings.set_value("remap", "importer", "texture")
		settings.set_value("remap", "type", "CompressedTexture2D")
		settings.set_value("params", "compress/mode", 0)
		settings.set_value("params", "mipmaps/generate", false)
		settings.set_value("params", "process/fix_alpha_border", false)
		if settings.save(destination + ".import") != OK:
			push_error("Cannot save inventory outline import settings: " + destination)
			quit(1)
			return
		hashes[texture.resource_path] = FileAccess.get_sha256(texture.resource_path)
		entries.append("\t%s: preload(%s)" % [JSON.stringify(texture.resource_path + ":" + str(region)), JSON.stringify(destination)])
	var script := FileAccess.open("res://scripts/inventory_outline_assets.gd", FileAccess.WRITE)
	if script == null:
		push_error("Cannot write inventory outline lookup")
		quit(1)
		return
	script.store_string("extends RefCounted\n\n# Generated by tools/generate_inventory_outlines.gd; do not edit.\nconst WIDTH := %s\nconst INPUT_HASHES := %s\nconst TEXTURES := {\n%s\n}\n" % [Baker.WIDTH, JSON.stringify(hashes, "\t"), ",\n".join(entries)])
	print("Generated %s inventory outline assets" % entries.size())
	quit()
