#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
MONITOR_REGION=ap-northeast-1

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$PROJECT_ROOT"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 is required before this wizard can continue"
    exit 1
  fi
}

set_supabase_monitor_secrets() {
  local canary_enabled="$1" secret_file
  secret_file=$(mktemp)
  chmod 600 "$secret_file"
  printf 'EDENIA_AUTH_MONITOR_TOKEN=%s\n' "$AUTH_MONITOR_TOKEN" > "$secret_file"
  printf 'EDENIA_AUTH_MONITOR_CANARY_ENABLED=%s\n' "$canary_enabled" >> "$secret_file"
  if ! supabase secrets set --env-file "$secret_file" >/dev/null; then
    rm -f -- "$secret_file"
    warn "Supabase rejected the monitor secrets"
    exit 1
  fi
  rm -f -- "$secret_file"
}

copy_monitor_token() {
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$AUTH_MONITOR_TOKEN" | pbcopy
    return
  fi
  if command -v clip.exe >/dev/null 2>&1; then
    printf '%s' "$AUTH_MONITOR_TOKEN" | clip.exe
    return
  fi
  warn "No supported clipboard command is available; stop rather than print the token"
  exit 1
}

clear_clipboard() {
  if command -v pbcopy >/dev/null 2>&1; then
    printf '' | pbcopy
  elif command -v clip.exe >/dev/null 2>&1; then
    printf '' | clip.exe
  fi
}

CANARY_ACTIVE=false

cleanup_sensitive_state() {
  local cleanup_secret_file

  clear_clipboard
  if [[ "$CANARY_ACTIVE" != "true" || -z "${AUTH_MONITOR_TOKEN:-}" ]]; then
    return
  fi

  warn "The wizard is exiting while the failure canary is enabled; attempting to disable it"
  cleanup_secret_file=$(mktemp)
  chmod 600 "$cleanup_secret_file"
  printf 'EDENIA_AUTH_MONITOR_TOKEN=%s\n' "$AUTH_MONITOR_TOKEN" > "$cleanup_secret_file"
  printf 'EDENIA_AUTH_MONITOR_CANARY_ENABLED=false\n' >> "$cleanup_secret_file"
  if supabase secrets set --env-file "$cleanup_secret_file" >/dev/null; then
    CANARY_ACTIVE=false
    note "failure canary disabled"
  else
    warn "automatic canary cleanup failed; disable EDENIA_AUTH_MONITOR_CANARY_ENABLED immediately"
  fi
  rm -f -- "$cleanup_secret_file"
}

trap cleanup_sensitive_state EXIT

monitor_http_status() {
  local method="$1"
  printf 'header = "Authorization: Bearer %s"\n' "$AUTH_MONITOR_TOKEN" \
    | curl --config - --silent --show-error --output /dev/null \
      --write-out '%{http_code}' --request "$method" "$MONITOR_ENDPOINT"
}

monitor_edge_region() {
  local method="$1"
  printf 'header = "Authorization: Bearer %s"\n' "$AUTH_MONITOR_TOKEN" \
    | curl --config - --silent --show-error --dump-header - --output /dev/null \
      --request "$method" "$MONITOR_ENDPOINT" \
    | awk 'tolower($1) == "x-sb-edge-region:" { gsub("\\r", "", $2); print $2 }'
}

banner "Edenia production Auth monitoring"

stage "Preflight and operator notification"
say "This provisions production monitoring. It never prints or writes the bearer token to the repository."
for required in git gh supabase openssl curl jq awk; do require_command "$required"; done
if ! gh auth status >/dev/null 2>&1; then
  warn "Authenticate gh before continuing"
  exit 1
fi
if [[ ! -f supabase/migrations/20260828041926_add_external_auth_monitor_bridge.sql \
   || ! -f supabase/functions/auth-health-monitor/index.ts ]]; then
  warn "Run this wizard from the merged monitoring repair commit"
  exit 1
fi
CURRENT_BRANCH=$(git branch --show-current)
if [[ "$CURRENT_BRANCH" != "master" ]]; then
  warn "Current branch is $CURRENT_BRANCH; production setup normally runs from merged master"
  confirm "Continue from this exact checkout?" || exit 1
fi
open_url "https://app.pulsetic.com/account/general-alerts/email"
step "Sign in or create the no-cost account; do not share its address or session here."
step "Confirm that the account email is verified and can receive monitor alerts."
step "Maintain a monthly reminder and sign in at least every 80 days so Pulsetic does not pause the Free account for inactivity."
pause "Continue only after the operator notification destination is ready."

stage "Deploy the production recorder and endpoint"
say "The migration is additive. The function stays unreachable without a dedicated 64-hex bearer token."
SUPABASE_URL=$(gh variable get SUPABASE_URL)
if [[ ! "$SUPABASE_URL" =~ ^https://[a-z0-9-]+\.supabase\.co/?$ ]]; then
  warn "The repository SUPABASE_URL variable is missing or invalid"
  exit 1
fi
SUPABASE_URL=${SUPABASE_URL%/}
PROJECT_REF=${SUPABASE_URL#https://}
PROJECT_REF=${PROJECT_REF%%.*}
DEPLOYED_REGION=$(supabase projects list --output json \
  | jq -r --arg project_ref "$PROJECT_REF" \
    '.[] | select(.id == $project_ref) | .region' \
  | head -n1)
if [[ -z "$DEPLOYED_REGION" || "$DEPLOYED_REGION" == "null" ]]; then
  warn "Could not verify the linked Supabase project region"
  exit 1
fi
if [[ "$DEPLOYED_REGION" != "$MONITOR_REGION" ]]; then
  warn "The deployed region is $DEPLOYED_REGION, but this repair expects $MONITOR_REGION"
  exit 1
fi
MONITOR_ENDPOINT="$SUPABASE_URL/functions/v1/auth-health-monitor?forceFunctionRegion=$MONITOR_REGION"
AUTH_MONITOR_TOKEN=$(openssl rand -hex 32)
if [[ ! "$AUTH_MONITOR_TOKEN" =~ ^[0-9a-f]{64}$ ]]; then
  warn "Could not generate the monitor token"
  exit 1
fi
supabase db push --linked --dry-run
confirm "Apply the pending production migration and deploy auth-health-monitor now?" || exit 1
supabase db push --linked
set_supabase_monitor_secrets false
supabase functions deploy auth-health-monitor --use-api
set_secret EDENIA_AUTH_MONITOR_TOKEN "$AUTH_MONITOR_TOKEN"
if ! gh secret list --json name --jq '.[].name' | grep -qx EDENIA_AUTH_MONITOR_TOKEN; then
  warn "The GitHub freshness-watchdog secret is not confirmed"
  exit 1
fi
say "Production migration, function, canary-off state, and GitHub watchdog secret are configured."

stage "Create the Independent Auth monitor"
open_url "https://app.pulsetic.com/monitors"
step "Create a temporary Website Monitoring monitor for: https://example.com"
step "Interval: 5 minutes. Notification delay: 0. Keep Email Alert enabled."
step "Save without entering the production endpoint or Auth monitor capability."
step "Open the temporary monitor, choose More, then open its saved Advanced Settings."
pause "Continue only after the temporary monitor exists and its saved Advanced Settings are open."
copy_monitor_token
step "In one saved update, set Name = Edenia production Auth and URL = $MONITOR_ENDPOINT"
step "Under Request set HTTP Method: POST"
step "Under Request Headers set Authorization = Bearer followed by the Auth monitor capability currently on your clipboard."
step "Under Response and Keywords set Expected statuses: 200"
step "Keep the five-minute interval, zero notification delay, and Email Alert enabled."
step "Verify Request Preview shows the production URL, POST, and the Authorization header without copying or sharing its value."
step "Update the monitor, run one check, and wait for it to become Online."
step "Confirm the temporary monitor was converted in place and no separate example.com monitor remains."
step "Success rule: keep the HTTP status check. The Edge Function returns 200 for healthy outcomes and 503 for monitor failures. Do not add JSON assertions."
step "Detection SLA: a continuous failure must produce the DOWN notification within 10 minutes of the last healthy check."
pause "Continue only after the converted production monitor is Online."
clear_clipboard
BASELINE_STATUS=$(monitor_http_status POST)
if [[ "$BASELINE_STATUS" != "200" ]]; then
  warn "The authenticated production probe returned HTTP $BASELINE_STATUS instead of 200"
  exit 1
fi
BASELINE_REGION=$(monitor_edge_region POST)
if [[ "$BASELINE_REGION" != "$MONITOR_REGION" ]]; then
  warn "The authenticated production probe ran in ${BASELINE_REGION:-an unknown region} instead of $MONITOR_REGION"
  exit 1
fi
say "The Auth health probe returned HTTP 200 from $MONITOR_REGION and recorded an aggregate probe."

stage "Rehearse provider failure and recovery"
warn "Keep the server profile-data gate off for this supervised rehearsal."
confirm "Is the server profile-data gate confirmed off?" || exit 1
confirm "Is the operator email verified and Email Alert enabled for Edenia production Auth?" || exit 1
confirm "Enable the bounded provider-failure canary now?" || exit 1
set_supabase_monitor_secrets true
CANARY_ACTIVE=true
open_url "https://app.pulsetic.com/monitors"
step "Open Edenia production Auth, choose More, open Advanced Settings, and add request header:"
step "X-Edenia-Auth-Monitor-Canary = provider_unavailable"
step "Do not alter the Authorization header. Update the monitor; confirmation retries must produce a real DOWN incident and open the three-failure aggregate alert."
pause "Continue only after the real DOWN notification is received."
confirm "Was the DOWN notification delivered within 10 minutes of the last healthy check?" || exit 1
step "Remove the X-Edenia-Auth-Monitor-Canary header and save the monitor."
confirm "Has the canary header been removed from Pulsetic?" || exit 1
set_supabase_monitor_secrets false
CANARY_ACTIVE=false
step "Wait for the real probe to return UP and close the aggregate alert."
confirm "Did the operator receive the real UP recovery notification?" || exit 1
RECOVERY_STATUS=$(monitor_http_status POST)
if [[ "$RECOVERY_STATUS" != "200" ]]; then
  warn "The post-canary production probe returned HTTP $RECOVERY_STATUS"
  exit 1
fi
say "The real DOWN and real UP notifications prove operator delivery. Canary is off, the custom header is removed, and the real provider probe is healthy."

stage "Prove freshness and the sustained cadence"
open_url "https://app.pulsetic.com/monitors"
step "Pause Edenia production Auth and note the UTC time outside any public issue."
step "Wait at least 11 minutes, then return here."
pause "Press Enter only after at least 11 minutes have elapsed."
STALE_STATUS=$(monitor_http_status GET)
if [[ "$STALE_STATUS" == "200" ]]; then
  warn "The aggregate status is still fresh; wait longer and rerun this stage"
  exit 1
fi
say "The authenticated freshness endpoint now fails closed with HTTP $STALE_STATUS."
open_url "https://github.com/BriceChivu/Edenia/actions/workflows/auth-health-monitor.yml"
step "Wait for the next delivered scheduled watchdog run and confirm that it fails on stale aggregate state."
pause "Continue only after the secondary hosted watchdog failure is visible."
step "Resume Edenia production Auth in Pulsetic with Run or Start and wait for Online."
pause "Continue after a fresh external probe returns the monitor and watchdog to healthy."
step "Leave the monitor active for at least 24 continuous hours, then return here."
pause "Press Enter after the 24-hour observation window is complete."
supabase db query --linked "with ordered as (select checked_at, lag(checked_at) over (order by checked_at) as prior_checked_at from private.auth_health_checks where checked_at >= pg_catalog.now() - interval '24 hours') select count(*) as check_count, min(checked_at) as window_start, max(checked_at) as window_end, round(max(extract(epoch from checked_at - prior_checked_at)) / 60.0, 2) as largest_gap_minutes from ordered;"
step "Confirm Pulsetic shows the five-minute monitor active throughout the same window."
step "Record only window start/end, count, largest gap, incident/recovery times, notification channel class, deployed commit, and pass/fail."
confirm "Is the largest aggregate gap at most 10 minutes with no unexplained Pulsetic gap?" || exit 1

finish
