const BASE_CURATED_CHANNEL_CATALOG = [
  {
    id: 'mandarin-grace',
    language: 'mandarin',
    input: '@GraceMandarinChinese',
    name: 'Grace Mandarin Chinese',
    levels: ['starting'],
    style: 'Clear explanations',
    description: 'Practical pronunciation, vocabulary, and culture lessons.'
  },
  {
    id: 'mandarin-espresso-chinese',
    language: 'mandarin',
    input: '@espressochinese',
    name: 'Espresso Chinese - John Wang',
    levels: ['starting'],
    style: 'Clear explanations'
  },
  {
    id: 'mandarin-everyday-chinese',
    language: 'mandarin',
    input: '@EverydayChinese',
    name: 'Everyday Chinese',
    levels: ['starting'],
    style: 'Structured lessons'
  },
  {
    id: 'mandarin-chinese-for-us',
    language: 'mandarin',
    input: '@ChineseForUsOfficial',
    name: 'ChineseFor.Us',
    levels: ['starting'],
    style: 'Structured lessons'
  },
  {
    id: 'mandarin-stickynote',
    language: 'mandarin',
    input: '@Stickynote.Chinese',
    name: 'Jun - Stickynote Chinese',
    levels: ['starting', 'beginner'],
    style: 'Comprehensible input'
  },
  {
    id: 'mandarin-harbin',
    language: 'mandarin',
    input: '@HarbinMandarin',
    name: 'Harbin Mandarin',
    levels: ['starting'],
    style: 'Comprehensible input'
  },
  {
    id: 'mandarin-xiaogua',
    language: 'mandarin',
    input: '@xiaoguachinese',
    name: 'Xiaogua Chinese',
    levels: ['beginner'],
    style: 'Comprehensible input'
  },
  {
    id: 'mandarin-lazy',
    language: 'mandarin',
    input: '@Lazy-Chinese',
    name: 'Lazy Chinese - Comprehensible Input',
    levels: ['beginner'],
    style: 'Comprehensible input'
  },
  {
    id: 'mandarin-chinese-with-ben',
    language: 'mandarin',
    input: '@chinesewithben',
    name: 'Chinese with Ben',
    levels: ['beginner'],
    style: 'Clear explanations'
  },
  {
    id: 'mandarin-richard-chinese',
    language: 'mandarin',
    input: '@RichardChineseLanguage',
    name: '理查老师的中文直播课 - Richard Chinese',
    levels: ['beginner'],
    style: 'Structured lessons'
  },
  {
    id: 'mandarin-chinese-at-dawn',
    language: 'mandarin',
    input: '@chinese-at-dawn',
    name: 'Chinese at Dawn',
    levels: ['beginner'],
    style: 'Comprehensible input'
  },
  {
    id: 'mandarin-dashu',
    language: 'mandarin',
    input: '@dashumandarin',
    name: 'Dashu Mandarin 大叔中文',
    levels: ['intermediate'],
    style: 'Conversations and interviews'
  },
  {
    id: 'mandarin-annie-kerin',
    language: 'mandarin',
    input: '@LearnChinesewithAnnieandKerin',
    name: '俩北京姑娘闲聊',
    levels: ['intermediate'],
    style: 'Casual conversations'
  },
  {
    id: 'mandarin-corner',
    language: 'mandarin',
    input: '@MandarinCorner2',
    name: 'Mandarin Corner',
    levels: ['intermediate'],
    style: 'Conversations and stories',
    description: 'Long-form listening, street interviews, and everyday Mandarin.'
  },
  {
    id: 'mandarin-free-to-learn',
    language: 'mandarin',
    input: '@DANLIAOFreeToLearnChinese',
    name: 'Free To Learn Chinese',
    levels: ['intermediate'],
    style: 'Natural Mandarin'
  },
  {
    id: 'mandarin-shenglan-podcast',
    language: 'mandarin',
    input: '@chinesepodcastwithshenglan',
    name: 'Chinese Podcast With Shenglan',
    levels: ['intermediate'],
    style: 'Podcast'
  },
  {
    id: 'mandarin-sophia-c',
    language: 'mandarin',
    input: '@sonargalc',
    name: 'Sophia C.',
    levels: ['intermediate'],
    style: 'Natural Mandarin'
  },
  {
    id: 'mandarin-out-of-office',
    language: 'mandarin',
    input: '@theOutofOfficePodcast',
    name: '不上班 / Out of Office',
    levels: ['advanced'],
    style: 'Podcast'
  },
  {
    id: 'mandarin-muerstalk',
    language: 'mandarin',
    input: '@muerstalk',
    name: '周慕姿放心說',
    levels: ['advanced'],
    style: 'Psychology and conversations'
  },
  {
    id: 'mandarin-bailingguo',
    language: 'mandarin',
    input: '@bailingguo',
    name: 'Bailingguo News',
    levels: ['advanced'],
    style: 'News and commentary'
  },
  {
    id: 'mandarin-mediastorm',
    language: 'mandarin',
    input: '@mediastorm6801',
    name: 'Mediastorm影视飓风',
    levels: ['advanced'],
    style: 'Film and technology'
  },
  {
    id: 'mandarin-hahatai',
    language: 'mandarin',
    input: '@Hahatai',
    name: 'HahaTai 哈哈台',
    levels: ['advanced'],
    style: 'Street interviews'
  },
  {
    id: 'mandarin-one-in-billion',
    language: 'mandarin',
    input: '@One-In-a-Billion',
    name: '亿点点不一样',
    levels: ['advanced'],
    style: 'Native entertainment'
  },
  {
    id: 'korean-comprehensible',
    language: 'korean',
    input: '@ComprehensibleInputKorean',
    name: 'Comprehensible Input Korean',
    levels: ['starting', 'beginner', 'intermediate'],
    style: 'Comprehensible input',
    description: 'Context-rich Korean listening for building natural comprehension.'
  },
  {
    id: 'korean-ttmik',
    language: 'korean',
    input: '@talktomeinkorean',
    name: 'Talk To Me In Korean',
    levels: ['starting', 'beginner', 'intermediate', 'advanced'],
    style: 'Lessons and conversations',
    description: 'A broad library of practical Korean lessons and native conversations.'
  },
  {
    id: 'spanish-dreaming',
    language: 'spanish',
    input: '@DreamingSpanish',
    name: 'Dreaming Spanish',
    levels: ['starting', 'beginner', 'intermediate', 'advanced'],
    style: 'Comprehensible input',
    description: 'Levelled Spanish immersion built around interesting, understandable videos.'
  },
  {
    id: 'spanish-easy',
    language: 'spanish',
    input: '@EasySpanish',
    name: 'Easy Spanish',
    levels: ['beginner', 'intermediate', 'advanced'],
    style: 'Street interviews',
    description: 'Authentic conversations with subtitles and learner-focused explanations.'
  },
  {
    id: 'german-easy',
    language: 'german',
    input: '@EasyGerman',
    name: 'Easy German',
    levels: ['beginner', 'intermediate', 'advanced'],
    style: 'Street interviews',
    description: 'Natural German conversations with bilingual subtitles.'
  },
  {
    id: 'german-lingoni',
    language: 'german',
    input: '@lingoniGERMAN',
    name: 'lingoni GERMAN',
    levels: ['starting', 'beginner', 'intermediate'],
    style: 'Structured lessons',
    description: 'Levelled grammar, vocabulary, and listening lessons.'
  },
]
const CURATED_CHANNEL_LEVEL_OVERRIDES = {
  'korean-comprehensible': ['starting'],
  'korean-ttmik': ['starting'],
  'spanish-dreaming': ['starting'],
  'spanish-easy': ['beginner'],
  'german-lingoni': ['starting'],
  'german-easy': ['beginner']
}
const EXPANDED_CURATED_CHANNEL_DATA = [
  ['japanese-pod101', 'japanese', '@JapanesePod101', 'Learn Japanese with JapanesePod101.com', 'starting', 'Structured lessons'],
  ['japanese-kanako-journey', 'japanese', '@KanakosJapaneseJourney', 'Kanako’s Japanese Journey! | かなこ', 'starting', 'Clear explanations'],
  ['japanese-mochi-real', 'japanese', '@mochirealjapanese3430', 'Mochi Real Japanese', 'starting', 'Comprehensible input'],
  ['japanese-learn-japanese-channel', 'japanese', '@LearnJapaneseChannel', 'Learn Japanese Channel', 'starting', 'Structured lessons'],
  ['japanese-yuta', 'japanese', '@ThatJapaneseManYuta', 'That Japanese Man Yuta', 'starting', 'Clear explanations'],
  ['japanese-sushi-room', 'japanese', '@sushiroomjapaneselesson689', 'SUSHI ROOM（Japanese Lesson）', 'starting', 'Structured lessons'],
  ['japanese-beginners-channel', 'japanese', '@JapaneseBeginnersChannel', 'Learn Japanese for beginners 【 あいう 】', 'beginner', 'Structured lessons'],
  ['japanese-japarrot', 'japanese', '@Japarrot_LetsLearnJP', "Japarrot!- Let's Learn Japanese", 'beginner', 'Comprehensible input'],
  ['japanese-shun', 'japanese', '@JapanesewithShun', 'Japanese with Shun', 'beginner', 'Podcast'],
  ['japanese-bonbon', 'japanese', '@bonbonsJapaneseLesson', "BonBon's Japanese Lesson", 'beginner', 'Clear explanations'],
  ['japanese-chibi', 'japanese', '@ChibiJapanese-z7r', 'Chibi Japanese', 'beginner', 'Comprehensible input'],
  ['japanese-ayano', 'japanese', '@am_japanese_vocab_beginners', '彩乃老師 / 日語入門單字與片語', 'beginner', 'Structured lessons'],
  ['japanese-taka-dojo', 'japanese', '@takanihongodojo', 'Taka Nihongo Dojo', 'intermediate', 'Clear explanations'],
  ['japanese-super-immersion', 'japanese', '@JSI55', 'Japanese super immersion', 'intermediate', 'Comprehensible input'],
  ['japanese-tanaka', 'japanese', '@japanese_tanakasan', 'Learn Japanese with Tanaka san', 'intermediate', 'Comprehensible input'],
  ['japanese-joy', 'japanese', '@JoyofJapanese', 'Ren – Joy of Japanese', 'intermediate', 'Comprehensible input'],
  ['japanese-speak-naturally', 'japanese', '@SpeakJapaneseNaturally', 'Speak Japanese Naturally', 'intermediate', 'Clear explanations'],
  ['japanese-chienowa', 'japanese', '@chienowajapanese1101', 'Chienowa Japanese', 'intermediate', 'Comprehensible input'],
  ['japanese-kevin', 'japanese', '@KevinsEnglishRoom', "Kevin's English Room / 掛山ケビ志郎", 'advanced', 'Native entertainment'],
  ['japanese-jiro', 'japanese', '@JiroJapanese', 'Jiro, just Japanese', 'advanced', 'Native entertainment'],
  ['japanese-atashinchi', 'japanese', '@Atashinchi', '【アニメ】あたしンち公式チャンネル', 'advanced', 'Native entertainment'],
  ['japanese-kohei', 'japanese', '@japanesewithKohei', 'ジャパラボ JapaneseLab Kohei', 'advanced', 'Casual conversations'],
  ['japanese-tbs-news-dig', 'japanese', '@tbsnewsdig', 'TBS NEWS DIG Powered by JNN', 'advanced', 'News and commentary'],
  ['japanese-tokai-on-air', 'japanese', '@TokaiOnAir', '東海オンエア', 'advanced', 'Native entertainment'],

  ['korean-gobilly', 'korean', '@GoBillyKorean', 'Learn Korean with GO! Billy Korean', 'beginner', 'Structured lessons'],
  ['korean-unnie', 'korean', '@KoreanUnnie', 'Korean Unnie', 'beginner', 'Clear explanations'],
  ['korean-prof-yoon', 'korean', '@ProfYoonsKoreanLanguageClass', "Prof. Yoon's Korean Language Class", 'beginner', 'Structured lessons'],
  ['korean-choisusu', 'korean', '@choisusu', 'Choisusu Korean', 'intermediate', 'Comprehensible input'],
  ['korean-tammy', 'korean', '@KoreanwithMissVicky', 'Korean with Miss Vicky', 'intermediate', 'Clear explanations'],
  ['korean-jream', 'korean', '@KoreanJream', 'Korean Jream', 'intermediate', 'Casual conversations'],
  ['korean-conversational', 'korean', '@ConversationalKorean', 'Conversational Korean', 'intermediate', 'Casual conversations'],
  ['korean-psick', 'korean', '@koreanenglishman', '영국남자 Korean Englishman', 'advanced', 'Native entertainment'],
  ['korean-ootb', 'korean', '@ootbstudio', 'ootb STUDIO', 'advanced', 'Native entertainment'],
  ['korean-mmtg', 'korean', '@MMTG', '문명특급 MMTG', 'advanced', 'Conversations and interviews'],
  ['korean-14f', 'korean', '@14f', '14F 일사에프', 'advanced', 'News and commentary'],
  ['korean-diggle', 'korean', '@Diggle', '디글 :Diggle', 'advanced', 'Native entertainment'],

  ['spanish-after-hours', 'spanish', '@spanishafterhours', 'Spanish After Hours', 'starting', 'Comprehensible input'],
  ['spanish-butterfly', 'spanish', '@ButterflySpanish', 'Butterfly Spanish', 'beginner', 'Clear explanations'],
  ['spanish-hola', 'spanish', '@HolaSpanish', 'Hola Spanish', 'beginner', 'Structured lessons'],
  ['spanish-how-to', 'spanish', '@SpanishlandSchool', 'Spanishland School', 'intermediate', 'Detailed lessons'],
  ['spanish-juan', 'spanish', '@espanolconjuan', 'Español con Juan', 'intermediate', 'Podcast'],
  ['spanish-erre', 'spanish', '@ErrequeELE', 'Erre que ELE', 'intermediate', 'Casual conversations'],
  ['spanish-vicente', 'spanish', '@SpanishwithVicente', 'Spanish with Vicente', 'intermediate', 'Clear explanations'],
  ['spanish-visualpolitik', 'spanish', '@VisualPolitik', 'VisualPolitik', 'advanced', 'News and commentary'],
  ['spanish-linguriosa', 'spanish', '@Linguriosa', 'Linguriosa', 'advanced', 'Clear explanations'],
  ['spanish-ter', 'spanish', '@Ter', 'Ter', 'advanced', 'Native entertainment'],
  ['spanish-quantum', 'spanish', '@QuantumFracture', 'QuantumFracture', 'advanced', 'Clear explanations'],
  ['spanish-dw', 'spanish', '@DWDocumental', 'DW Documental', 'advanced', 'News and commentary'],
  ['spanish-pod101', 'spanish', 'https://youtube.com/c/spanishpod101', 'SpanishPod101', 'starting', 'Structured lessons'],
  ['spanish-aprender-idiomas', 'spanish', 'UCFS0eRHTcchOpM-FCck7pGA', 'Aprender Idiomas – Learn Languages', 'starting', 'Structured lessons'],
  ['spanish-learn-martin', 'spanish', 'https://youtube.com/user/learnspanish1', 'Learn Spanish (Martin)', 'starting', 'Structured lessons'],
  ['spanish-culture-alley', 'spanish', '@culturealley', 'Culture Alley', 'starting', 'Structured lessons'],
  ['spanish-playground', 'spanish', 'https://youtube.com/user/SpanishPlayground', 'Spanish Playground', 'starting', 'Comprehensible input'],
  ['spanish-tio', 'spanish', 'UCyqfGTu-9hL3OBkiCKogJuA', 'Tio Spanish', 'starting', 'Clear explanations'],
  ['spanish-rock-n-learn', 'spanish', 'https://youtube.com/c/rocknlearn', "Rock 'N Learn", 'starting', 'Structured lessons'],
  ['spanish-babyfirst', 'spanish', 'UCW0fLAGU31dyY7PDgjCs0pQ', 'BabyFirst Español', 'starting', 'Comprehensible input'],
  ['spanish-basho-friends', 'spanish', 'UCMdV1ynMzE4y0NoeTZa7GZA', 'Basho & Friends', 'starting', 'Comprehensible input'],
  ['spanish-academy-tv', 'spanish', 'UCYR9NiM3qzfczomiJdAw83Q', 'Spanish Academy TV', 'starting', 'Structured lessons'],
  ['spanish-classical-casa', 'spanish', 'UCWNZScV2Zim7tq7wJ0gmdVg', 'Classical Casa', 'starting', 'Comprehensible input'],
  ['spanish-speak-faster', 'spanish', 'UC0Oq6ZwNKq8eJuQdiRdMxcA', 'Speak Spanish Faster', 'beginner', 'Structured lessons'],
  ['spanish-light-speed', 'spanish', 'https://youtube.com/user/LightSpeedSpanish', 'Light Speed Spanish', 'beginner', 'Structured lessons'],
  ['spanish-language-tutor', 'spanish', 'UC_GFwrcNlXh92xA8iKFT2WA', 'The Language Tutor', 'beginner', 'Structured lessons'],
  ['spanish-dude', 'spanish', '@elspanishdude', 'The Spanish Dude', 'beginner', 'Clear explanations'],
  ['spanish-with-paul', 'spanish', 'https://youtube.com/user/learnspanishvideos', 'Spanish with Paul', 'beginner', 'Structured lessons'],
  ['spanish-senor-jordan', 'spanish', 'https://youtube.com/c/SeñorJordan', 'Señor Jordan', 'beginner', 'Structured lessons'],
  ['spanish-spring', 'spanish', 'UCjnIhuq24374DetprE-6dQg', 'Spring Spanish', 'beginner', 'Structured lessons'],
  ['spanish-fluentu', 'spanish', 'https://youtube.com/user/FluentUSpanish', 'FluentU Spanish', 'beginner', 'Structured lessons'],
  ['spanish-made-easy', 'spanish', 'https://youtube.com/c/SpanishMadeEasySugarAstronaut', 'Sugar Astronaut / Spanish Made Easy', 'beginner', 'Structured lessons'],
  ['spanish-real-world-lessons', 'spanish', 'UC4xouAB7u2_Ym0LxJtZ3xfw', 'Real World Spanish Lessons', 'beginner', 'Comprehensible input'],
  ['spanish-why-not', 'spanish', 'UCIdFcLCIJQ_YMrormG_nU8w', 'Why Not Spanish?', 'intermediate', 'Casual conversations'],
  ['spanish-notes', 'spanish', 'https://youtube.com/user/spanishben', 'Notes in Spanish', 'intermediate', 'Podcast'],
  ['spanish-videoele', 'spanish', 'https://youtube.com/c/AgustinIruela', 'VideoEle (Agustín Iruela)', 'intermediate', 'Detailed lessons'],
  ['spanish-fundeu', 'spanish', 'https://youtube.com/user/Fundeu', 'FundéuRAE', 'intermediate', 'Clear explanations'],
  ['spanish-podcast-net', 'spanish', 'UCpfjMrPcCxl6aP7qIkN8Jpg', 'Spanishpodcast.net', 'intermediate', 'Podcast'],
  ['spanish-maria-espanol', 'spanish', 'UC30I0ZZ54oOVBYeXJtafYIA', 'María Español', 'intermediate', 'Clear explanations'],
  ['spanish-and-go', 'spanish', 'UCjTIEnsvhWPvrBqtRkB1cLA', 'Spanish and Go', 'intermediate', 'Casual conversations'],
  ['spanish-around', 'spanish', 'UClSd_O2_IqGmmo_lbtJ1uJw', 'Spanish Around', 'intermediate', 'Comprehensible input'],
  ['spanish-con-maria', 'spanish', 'UCiCwYsOVt-EirMwYht345MQ', 'Español con María', 'intermediate', 'Clear explanations'],
  ['spanish-mexitalki', 'spanish', 'UCeJguGZvG8yKQW6ZAgG060Q', 'Mexitalki', 'intermediate', 'Casual conversations'],
  ['spanish-use-your', 'spanish', 'UCwHfD66WY-tG9FqI68ZMhWg', 'Use Your Spanish', 'intermediate', 'Comprehensible input'],
  ['spanish-bilingue-blogs', 'spanish', 'UCa57CLZlqhFtn1m-e-tWhpg', 'Bilingüe Blogs', 'intermediate', 'Casual conversations'],
  ['spanish-like-a-pro', 'spanish', 'UClGuN_roGD3AfEUVehKiVGw', 'Spanish Like a Pro!', 'intermediate', 'Comprehensible input'],
  ['spanish-lingustv', 'spanish', '@LingusTV', 'LingusTV', 'intermediate', 'Comprehensible input'],
  ['spanish-holasoygerman', 'spanish', 'https://youtube.com/user/HolaSoyGerman', 'HolaSoyGerman', 'advanced', 'Native entertainment'],
  ['spanish-juegagerman', 'spanish', 'UCYiGq8XF7YQD00x7wAd62Zg', 'JuegaGerman', 'advanced', 'Native entertainment'],
  ['spanish-fernanfloo', 'spanish', 'UCV4xOVpbcV8SdueDCOxLXtQ', 'Fernanfloo', 'advanced', 'Native entertainment'],
  ['spanish-elrubius', 'spanish', 'UCXazgXDIYyWH-yXLAkcrFxw', 'elrubiusOMG', 'advanced', 'Native entertainment'],
  ['spanish-luisito', 'spanish', 'https://youtube.com/user/LuisitoComunicaa', 'Luisito Comunica', 'advanced', 'Native entertainment'],
  ['spanish-enchufe-tv', 'spanish', 'https://youtube.com/user/enchufetv', 'Enchufe TV', 'advanced', 'Native entertainment'],
  ['spanish-yuya', 'spanish', 'https://youtube.com/user/lady16makeup', 'Yuya', 'advanced', 'Native entertainment'],
  ['spanish-genial', 'spanish', 'UCbrd1vu4_7qIE6IPV_dA-OA', 'Genial', 'advanced', 'Clear explanations'],
  ['spanish-curiosamente', 'spanish', 'UCX16cLWl6dCjlZMgUBxgGkA', 'CuriosaMente', 'advanced', 'Clear explanations'],
  ['spanish-xpress-tv', 'spanish', 'https://youtube.com/c/XpressTV', 'Xpress TV', 'advanced', 'Native entertainment'],
  ['spanish-magic-markers', 'spanish', 'UCjxeK_mixc2-AvWUSmqe1gg', 'Magic Markers', 'advanced', 'Clear explanations'],
  ['spanish-vice', 'spanish', 'UCYB6UxeSTHJyEMq-clobnrg', 'Vice en Español', 'advanced', 'News and commentary'],
  ['spanish-antonio-villaran', 'spanish', 'UCDupeqPlIEnjmtPmUEvgvLg', 'Antonio García Villarán', 'advanced', 'Clear explanations'],
  ['spanish-casi-creativo', 'spanish', 'https://youtube.com/user/fredlammie', 'Fred Lammie / Casi Creativo', 'advanced', 'Native entertainment'],
  ['spanish-the-flama', 'spanish', '@theflama', 'The Flama', 'advanced', 'Native entertainment'],
  ['spanish-cinexceso', 'spanish', 'https://youtube.com/user/MefeKMR', 'Cinexceso', 'advanced', 'Native entertainment'],
  ['spanish-pulso-pop', 'spanish', 'https://youtube.com/c/PulsoPOPNewsTV', 'PULSO Pop News', 'advanced', 'News and commentary'],
  ['spanish-buzzfeed-latam', 'spanish', 'https://youtube.com/c/buzzfeedlatam', 'BuzzFeed LATAM', 'advanced', 'Native entertainment'],
  ['spanish-consigue-trabajo', 'spanish', 'UCo4y77YI2ZurvvABWIq9oOQ', 'Consigue tu Trabajo', 'advanced', 'Clear explanations'],
  ['spanish-ruta-garnacha', 'spanish', 'https://youtube.com/user/vpedoardo', 'La Ruta de la Garnacha', 'advanced', 'Native entertainment'],
  ['spanish-recetas-cocina', 'spanish', 'https://youtube.com/c/recetasdecocinavideos', 'Recetas de Cocina', 'advanced', 'Native entertainment'],
  ['spanish-dare-to-diy', 'spanish', 'https://youtube.com/user/DaretoDIY', 'Dare to DIY', 'advanced', 'Native entertainment'],

  ['french-pod101', 'french', '@frenchpod101', 'Learn French with FrenchPod101.com', 'starting', 'Structured lessons'],
  ['french-poodle', 'french', '@french-with-poodle', 'French with Poodle', 'starting', 'Clear explanations'],
  ['french-leo', 'french', '@LeoFrenchTeacher', 'Leo French Teacher', 'starting', 'Clear explanations'],
  ['french-learn-with-fun', 'french', '@LearnFrench-9', 'Learn French With Fun', 'starting', 'Structured lessons'],
  ['french-dylane', 'french', '@TheperfectfrenchwithDylane', 'The perfect French with Dylane', 'starting', 'Detailed lessons'],
  ['french-lexie', 'french', '@LearnFrenchwithLexie', 'Learn French with Lexie', 'starting', 'Clear explanations'],
  ['french-nlf', 'french', '@NLF-Academy', 'NLF Academy | Real French Classes', 'beginner', 'Structured lessons'],
  ['french-alexa', 'french', '@learnfrenchwithalexa', 'Learn French With Alexa', 'beginner', 'Structured lessons'],
  ['french-piece', 'french', '@pieceoffrench', 'Piece of French', 'beginner', 'Casual conversations'],
  ['french-elisabeth', 'french', '@elisabeth_hellofrench', 'Learn French with Elisabeth - HelloFrench', 'beginner', 'Clear explanations'],
  ['french-facile', 'french', '@FrenchFacile12', 'French Facile', 'beginner', 'Comprehensible input'],
  ['french-adeline', 'french', '@AdelineTalks', 'Adeline Talks', 'beginner', 'Clear explanations'],
  ['french-input', 'french', '@FrenchComprehensibleInput', 'French Comprehensible Input', 'intermediate', 'Comprehensible input'],
  ['french-alice', 'french', '@aliceayel', 'alice ayel', 'intermediate', 'Comprehensible input'],
  ['french-school-tv', 'french', '@FrenchSchoolTV', 'French School TV', 'intermediate', 'Structured lessons'],
  ['french-easy', 'french', '@EasyFrench', 'Easy French', 'intermediate', 'Street interviews'],
  ['french-inner', 'french', '@innerFrench', 'innerFrench', 'intermediate', 'Podcast'],
  ['french-elisa', 'french', '@FrenchmorningswithElisa', 'French mornings with Elisa', 'intermediate', 'Clear explanations'],
  ['french-konbini', 'french', '@konbini', 'Konbini', 'advanced', 'Conversations and interviews'],
  ['french-palmashow', 'french', '@Palmashow', 'Palmashow', 'advanced', 'Native entertainment'],
  ['french-studio-bagel', 'french', '@StudioBagel', 'Studio Bagel', 'advanced', 'Native entertainment'],
  ['french-tv5monde', 'french', '@TV5MONDEInfo', 'TV5MONDE Info', 'advanced', 'News and commentary'],
  ['french-arte', 'french', '@arte', 'ARTE', 'advanced', 'News and commentary'],
  ['french-planete-rap', 'french', '@PlaneteRap', 'Planète Rap', 'advanced', 'Conversations and interviews'],

  ['german-naturlich', 'german', '@naturlichgerman2021', 'Natürlich German', 'starting', 'Comprehensible input'],
  ['german-teacher', 'german', '@yourgermanteacher', 'YourGermanTeacher', 'beginner', 'Structured lessons'],
  ['german-anja', 'german', '@LearnGermanwithAnja', 'Learn German with Anja', 'beginner', 'Clear explanations'],
  ['german-marija', 'german', '@DeutschmitMarija', 'Deutsch mit Marija', 'intermediate', 'Detailed lessons'],
  ['german-lera', 'german', '@DeutschLera', 'DeutschLera', 'intermediate', 'Clear explanations'],
  ['german-benjamin', 'german', '@BenjaminDerDeutschlehrer', 'Benjamin - Der Deutschlehrer', 'intermediate', 'Detailed lessons'],
  ['german-deutsch1', 'german', '@deutsch1', 'Deutsch1', 'intermediate', 'Structured lessons'],
  ['german-wissen2go', 'german', '@MrWissen2go', 'MrWissen2go', 'advanced', 'News and commentary'],
  ['german-kurzgesagt', 'german', '@KurzgesagtDE', 'Dinge Erklärt – Kurzgesagt', 'advanced', 'Clear explanations'],
  ['german-simplicissimus', 'german', '@Simplicissimus', 'Simplicissimus', 'advanced', 'News and commentary'],
  ['german-lesch', 'german', '@TerraXLeschundCo', 'Terra X Lesch & Co', 'advanced', 'Clear explanations'],
  ['german-dw', 'german', '@dwdeutsch', 'DW Deutsch', 'advanced', 'News and commentary'],
  ['german-pod101', 'german', 'https://youtube.com/user/germanpod101', 'GermanPod101', 'starting', 'Structured lessons'],
  ['german-dw-learn', 'german', 'UCxUWIEL-USsiPak0Qy6_vVg', 'Learn German with the DW', 'starting', 'Structured lessons'],
  ['german-goethe-institut', 'german', 'https://youtube.com/user/goetheinstitut', 'The Goethe-Institut', 'starting', 'Structured lessons'],
  ['german-slideshow-lessons', 'german', 'UCaeT58uDMlPpBlwAYaxN0LA', 'Learn German', 'starting', 'Structured lessons'],
  ['german-easy-online', 'german', 'https://youtube.com/user/easyonlinegermancom', 'Easy Online German', 'starting', 'Structured lessons'],
  ['german-free-lessons', 'german', 'UCvoOXEy-sAHbOXLshJr61yQ', 'Free German Lessons', 'starting', 'Structured lessons'],
  ['german-learn-fast', 'german', 'UCo9Gn1M2cLjnYT2gW9YOu9Q', 'Learn German Fast', 'starting', 'Structured lessons'],
  ['german-hallo-deutschschule', 'german', 'https://youtube.com/c/HalloDeutschschuleZürich', 'Hallo Deutschschule', 'starting', 'Comprehensible input'],
  ['german-deutsch-verstehen', 'german', 'UCJ-9bH9B1KZuXO988Vd56AA', 'Deutsch Verstehen', 'starting', 'Comprehensible input'],
  ['german-short-stories', 'german', 'UCfICLkXJnzcDDc3I7S6f9QA', 'My German Short Stories', 'starting', 'Comprehensible input'],
  ['german-uwe-kind', 'german', 'UCSxVWwSznSyOctmVLBEKEWw', 'Uwe Kind & LingoTech', 'starting', 'Comprehensible input'],
  ['german-through-music', 'german', 'UCFV-9HdgROeTPyci6g0AHTA', 'Learn German Through Music', 'starting', 'Comprehensible input'],
  ['german-bookbox', 'german', 'UCHEzhKyjlp60u0Kgqc_ikNA', 'BookBox German', 'starting', 'Comprehensible input'],
  ['german-blitztag1', 'german', 'https://youtube.com/user/blitztag1', 'Blitztag1', 'starting', 'Structured lessons'],
  ['german-fluentu', 'german', '@FluentUGerman', 'FluentU German', 'starting', 'Structured lessons'],
  ['german-deutsch-fuer-euch', 'german', 'https://youtube.com/user/DeutschFuerEuch', 'Deutsch für Euch', 'beginner', 'Clear explanations'],
  ['german-get-germanized', 'german', 'https://youtube.com/user/MeisterLehnsherr', 'Get Germanized', 'beginner', 'Clear explanations'],
  ['german-smartergerman', 'german', 'https://youtube.com/user/smartergerman', 'smarterGerman', 'beginner', 'Structured lessons'],
  ['german-herr-antrim', 'german', 'https://youtube.com/user/MrLAntrim', 'Learn German with Herr Antrim', 'beginner', 'Detailed lessons'],
  ['german-froehlich', 'german', 'https://youtube.com/c/froehlichDeutsch', 'fröhlich Deutsch', 'beginner', 'Clear explanations'],
  ['german-deutsch-happen', 'german', 'https://youtube.com/user/DeutschHappen', 'Deutsch Happen', 'beginner', 'Structured lessons'],
  ['german-girls4teaching', 'german', 'https://youtube.com/user/girl4teaching', 'Girls4Teaching', 'beginner', 'Structured lessons'],
  ['german-mit-julia', 'german', 'https://youtube.com/user/meroba34', 'DeutschMitJulia', 'beginner', 'Structured lessons'],
  ['german-business-vasilena', 'german', 'UCYvWsIn4Dc3GGAv8rymiG6Q', 'Business Deutsch mit Vasilena Petkova', 'intermediate', 'Detailed lessons'],
  ['german-dont-trust-rabbit', 'german', 'UC1-MpIG20o6kzsu1I5SLXpQ', 'DontTrustTheRabbit', 'intermediate', 'Casual conversations'],
  ['german-vlogdave', 'german', 'UCnZ0C4deOyB_TUFSJK3L4lg', 'German with VlogDave', 'intermediate', 'Casual conversations'],
  ['german-slow', 'german', 'UCXntXBt2YKBO1xDni0EgjXA', 'Slow German', 'intermediate', 'Comprehensible input'],
  ['german-julien-bam', 'german', 'UCTXeJ33DzXI2veQpKfrvaYw', 'Julien Bam', 'advanced', 'Native entertainment'],
  ['german-gronkh', 'german', 'https://youtube.com/Gronkh', 'Gronkh', 'advanced', 'Native entertainment'],
  ['german-feli', 'german', 'https://youtube.com/c/FelifromGermany', 'Feli from Germany', 'advanced', 'Conversations and interviews'],
  ['german-life-to-go', 'german', 'UCjAMG2jrP5ZEzCK4obm203g', 'Life to Go', 'advanced', 'Native entertainment'],
  ['german-leeroy', 'german', 'UCDW1yldFKWrfjrr78aP5Nkw', "Leeroy will's wissen!", 'advanced', 'Conversations and interviews'],
  ['german-ultralativ', 'german', 'https://youtube.com/c/Ultralativ', 'Ultralativ', 'advanced', 'News and commentary'],
  ['german-authentic-learning', 'german', 'UCcNBwmeFr0IeLVlP_49glrA', 'Authentic German Learning', 'advanced', 'Comprehensible input'],
  ['german-gute-arbeit', 'german', 'UCzdtr1q2eNmtc0z5lSPia_Q', 'Gute Arbeit Originals', 'advanced', 'Native entertainment'],

  ['english-bbc', 'english', '@bbclearningenglish', 'BBC Learning English', 'beginner', 'Structured lessons'],
  ['english-maria', 'english', '@EnglishWithMariaFicano', 'English with Maria', 'beginner', 'Clear explanations'],
  ['english-cozy-chat', 'english', '@englishcozychat', 'English Cozy Chat', 'beginner', 'Casual conversations'],
  ['english-volka', 'english', '@VolkaEnglish', 'Volka English', 'beginner', 'Comprehensible input'],
  ['english-slow-podcast', 'english', '@Slow_English_Podcast', 'Miss Honey 🍯', 'beginner', 'Podcast'],
  ['english-lukes-podcast', 'english', '@LukesEnglishPodcast', "Luke's English Podcast", 'beginner', 'Podcast'],
  ['english-high-level-listening', 'english', '@highlevellistening', 'High Level Listening Advanced English Podcast', 'intermediate', 'Podcast'],
  ['english-easy', 'english', '@EasyEnglishVideos', 'Easy British English', 'intermediate', 'Street interviews'],
  ['english-lucy', 'english', '@EnglishwithLucy', 'English with Lucy', 'intermediate', 'Clear explanations'],
  ['english-vanessa', 'english', '@SpeakEnglishWithVanessa', 'Speak English With Vanessa', 'intermediate', 'Clear explanations'],
  ['english-class101', 'english', '@EnglishClass101', 'Learn English with EnglishClass101.com', 'intermediate', 'Structured lessons'],
  ['english-tv-series', 'english', '@LearnEnglishWithTVSeries', 'Learn English With TV Series', 'intermediate', 'Comprehensible input'],
  ['english-fallon', 'english', '@fallontonight', 'The Tonight Show Starring Jimmy Fallon', 'advanced', 'Native entertainment'],
  ['english-bbc-news', 'english', '@BBCNews', 'BBC News', 'advanced', 'News and commentary'],
  ['english-bad-friends', 'english', '@BadFriends', 'Bad Friends', 'advanced', 'Casual conversations'],
  ['english-comedy-central-stand-up', 'english', '@standup', 'Comedy Central Stand-Up', 'advanced', 'Native entertainment'],
  ['english-comedy-central', 'english', '@ComedyCentral', 'Comedy Central', 'advanced', 'Native entertainment'],
  ['english-bbc-earth', 'english', '@bbcearth', 'BBC Earth', 'advanced', 'Clear explanations']
]
const EXPANDED_CURATED_CHANNEL_CATALOG = EXPANDED_CURATED_CHANNEL_DATA.map(([id, language, input, name, level, style]) => ({
  id,
  language,
  input,
  name,
  levels: [level],
  style
}))
export const CURATED_CHANNEL_CATALOG = [
  ...BASE_CURATED_CHANNEL_CATALOG.map(channel => ({
    ...channel,
    levels: CURATED_CHANNEL_LEVEL_OVERRIDES[channel.id] || channel.levels
  })),
  ...EXPANDED_CURATED_CHANNEL_CATALOG
]
export const CURATED_CHANNEL_SEARCH_LANGUAGE_ALIASES = {
  mandarin: ['mandarin', 'mandarin chinese', 'chinese', '中文', '汉语', '漢語'],
  japanese: ['japanese', '日本語'],
  korean: ['korean', '한국어'],
  spanish: ['spanish', 'espanol', 'español'],
  french: ['french', 'francais', 'français'],
  german: ['german', 'deutsch'],
  english: ['english'],
  russian: ['russian', 'русский'],
  portuguese: ['portuguese', 'portugues', 'português']
}
export const CURATED_CHANNEL_SEARCH_IGNORED_WORDS = new Set([
  'a',
  'channel',
  'channels',
  'for',
  'language',
  'languages',
  'learn',
  'learning',
  'lesson',
  'lessons',
  'the',
  'to',
  'video',
  'videos',
  'with',
  'youtube'
])
export const CURATED_NOT_SURE_CHANNEL_IDS = {
  mandarin: [
    'mandarin-grace',
    'mandarin-stickynote',
    'mandarin-lazy',
    'mandarin-chinese-at-dawn',
    'mandarin-chinese-with-ben',
    'mandarin-corner'
  ],
  english: [
    'english-bbc',
    'english-maria',
    'english-cozy-chat',
    'english-high-level-listening',
    'english-easy',
    'english-fallon'
  ],
  french: [
    'french-pod101',
    'french-poodle',
    'french-leo',
    'french-nlf',
    'french-alexa',
    'french-input'
  ]
}
