-- Prepare provider-neutral unsubscribe and suppression safety without adding an
-- email provider, public endpoint, Cron job, or live delivery path. Opaque
-- unsubscribe values are generated by a future server worker; only their
-- SHA-256 digests are persisted here.
create table private.reminder_suppressions (
  user_id uuid primary key,
  reason text not null,
  source text not null,
  suppressed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint reminder_suppressions_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete cascade,
  constraint reminder_suppressions_reason_check check (
    reason in ('unsubscribed', 'hard_bounce', 'complaint', 'manual')
  ),
  constraint reminder_suppressions_source_check check (
    source in ('unsubscribe_token', 'provider_webhook', 'operator')
  )
);

comment on table private.reminder_suppressions is
  'Server-owned recipient suppression state. Contains no email address or provider payload.';

create table private.reminder_unsubscribe_tokens (
  token_digest bytea primary key,
  delivery_id uuid not null unique,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  consumed_at timestamptz,
  constraint reminder_unsubscribe_tokens_delivery_id_fkey
    foreign key (delivery_id) references private.reminder_deliveries (id)
      on delete cascade,
  constraint reminder_unsubscribe_tokens_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete cascade,
  constraint reminder_unsubscribe_tokens_digest_check check (
    octet_length(token_digest) = 32
  ),
  constraint reminder_unsubscribe_tokens_consumed_at_check check (
    consumed_at is null or consumed_at >= created_at
  )
);

comment on table private.reminder_unsubscribe_tokens is
  'Single-use unsubscribe capabilities stored only as SHA-256 digests and bound to one occurrence.';

create index reminder_unsubscribe_tokens_user_id_idx
  on private.reminder_unsubscribe_tokens (user_id);

alter table private.reminder_suppressions enable row level security;
alter table private.reminder_unsubscribe_tokens enable row level security;

revoke all on table private.reminder_suppressions
  from public, anon, authenticated, service_role;
revoke all on table private.reminder_unsubscribe_tokens
  from public, anon, authenticated, service_role;

create or replace function private.apply_reminder_suppression(
  p_user_id uuid,
  p_reason text,
  p_source text,
  p_suppressed_at timestamptz
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $$
begin
  if p_user_id is null or p_suppressed_at is null then
    return false;
  end if;
  if not exists (
    select 1
    from auth.users as auth_user
    where auth_user.id = p_user_id
  ) then
    return false;
  end if;

  insert into private.reminder_suppressions (
    user_id,
    reason,
    source,
    suppressed_at
  ) values (
    p_user_id,
    p_reason,
    p_source,
    p_suppressed_at
  )
  on conflict (user_id) do nothing;

  update public.reminder_preferences as preference
  set enabled = false,
      consent_revoked_at = coalesce(
        preference.consent_revoked_at,
        p_suppressed_at
      ),
      updated_at = p_suppressed_at
  where preference.user_id = p_user_id;

  update private.reminder_deliveries as delivery
  set status = 'suppressed',
      claim_token = null,
      lease_expires_at = null,
      suppressed_at = p_suppressed_at,
      updated_at = p_suppressed_at
  where delivery.user_id = p_user_id
    and delivery.status in ('pending', 'claimed');

  return exists (
    select 1
    from private.reminder_suppressions as suppression
    where suppression.user_id = p_user_id
  );
end;
$$;

revoke execute on function private.apply_reminder_suppression(
  uuid, text, text, timestamptz
) from public, anon, authenticated, service_role;

alter table private.reminder_deliveries
  add column suppressed_at timestamptz;

alter table private.reminder_deliveries
  drop constraint reminder_deliveries_status_check,
  add constraint reminder_deliveries_status_check check (
    status in ('pending', 'claimed', 'dry_run_observed', 'suppressed')
  ),
  add constraint reminder_deliveries_suppressed_state_check check (
    (status = 'suppressed') = (suppressed_at is not null)
  );

-- This replaces only the existing claim implementation. It keeps the same RPC
-- signature and lease behavior while refusing both new and already-materialized
-- work for suppressed recipients.
create or replace function public.claim_due_reminder_deliveries(
  p_now timestamptz default now(),
  p_batch_size integer default 50,
  p_due_window_seconds integer default 900,
  p_lease_seconds integer default 120
)
returns table (
  delivery_id uuid,
  claim_token uuid,
  user_id uuid,
  scheduled_local_date date,
  scheduled_for timestamptz,
  timezone text,
  locale text,
  consent_version text,
  attempt_count integer
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if p_now is null then
    raise exception 'reminder_claim_now_required' using errcode = '22023';
  end if;
  if p_batch_size < 1 or p_batch_size > 100 then
    raise exception 'reminder_claim_batch_out_of_range' using errcode = '22023';
  end if;
  if p_due_window_seconds < 60 or p_due_window_seconds > 3600 then
    raise exception 'reminder_claim_due_window_out_of_range' using errcode = '22023';
  end if;
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'reminder_claim_lease_out_of_range' using errcode = '22023';
  end if;

  insert into private.reminder_deliveries (
    user_id,
    scheduled_local_date,
    scheduled_local_time,
    scheduled_for,
    timezone,
    locale,
    consent_version,
    consent_granted_at
  )
  select
    preference.user_id,
    occurrence.scheduled_local_date,
    preference.local_time,
    occurrence.scheduled_for,
    preference.timezone,
    preference.locale,
    preference.consent_version,
    preference.consent_granted_at
  from public.reminder_preferences as preference
  join private.reminder_delivery_testers as tester
    on tester.user_id = preference.user_id
  cross join lateral private.reminder_next_occurrence(
    preference.days,
    preference.local_time,
    preference.timezone,
    p_now - pg_catalog.make_interval(secs => p_due_window_seconds)
  ) as occurrence
  where preference.enabled
    and preference.consent_granted_at is not null
    and preference.consent_revoked_at is null
    and not exists (
      select 1
      from private.reminder_suppressions as suppression
      where suppression.user_id = preference.user_id
    )
    and occurrence.scheduled_for <= p_now
  on conflict on constraint reminder_deliveries_user_local_date_key do nothing;

  return query
  with candidates as materialized (
    select delivery.id
    from private.reminder_deliveries as delivery
    join private.reminder_delivery_testers as tester
      on tester.user_id = delivery.user_id
    join public.reminder_preferences as preference
      on preference.user_id = delivery.user_id
    where delivery.scheduled_for <= p_now
      and (
        delivery.status = 'pending'
        or (
          delivery.status = 'claimed'
          and delivery.lease_expires_at <= p_now
        )
      )
      and preference.enabled
      and preference.consent_granted_at is not null
      and preference.consent_revoked_at is null
      and not exists (
        select 1
        from private.reminder_suppressions as suppression
        where suppression.user_id = delivery.user_id
      )
      and preference.timezone = delivery.timezone
      and preference.local_time = delivery.scheduled_local_time
      and preference.locale = delivery.locale
      and preference.consent_version = delivery.consent_version
      and preference.consent_granted_at = delivery.consent_granted_at
      and extract(
        isodow from delivery.scheduled_local_date
      )::smallint = any(preference.days)
    order by delivery.scheduled_for, delivery.id
    for update of delivery skip locked
    limit p_batch_size
  ),
  claimed as (
    update private.reminder_deliveries as delivery
    set status = 'claimed',
        claim_token = gen_random_uuid(),
        lease_expires_at = p_now
          + pg_catalog.make_interval(secs => p_lease_seconds),
        attempt_count = delivery.attempt_count + 1,
        last_claimed_at = p_now,
        updated_at = p_now
    from candidates
    where delivery.id = candidates.id
    returning delivery.*
  )
  select
    claimed.id,
    claimed.claim_token,
    claimed.user_id,
    claimed.scheduled_local_date,
    claimed.scheduled_for,
    claimed.timezone,
    claimed.locale,
    claimed.consent_version,
    claimed.attempt_count
  from claimed
  order by claimed.scheduled_for, claimed.id;
end;
$$;

create or replace function public.store_reminder_unsubscribe_token(
  p_delivery_id uuid,
  p_token_digest bytea,
  p_created_at timestamptz default now()
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_existing_digest bytea;
begin
  if p_delivery_id is null
      or p_token_digest is null
      or octet_length(p_token_digest) <> 32
      or p_created_at is null then
    return false;
  end if;

  select token.token_digest
  into v_existing_digest
  from private.reminder_unsubscribe_tokens as token
  where token.delivery_id = p_delivery_id
  for update;

  if found then
    return v_existing_digest = p_token_digest;
  end if;

  insert into private.reminder_unsubscribe_tokens (
    token_digest,
    delivery_id,
    user_id,
    created_at
  )
  select
    p_token_digest,
    delivery.id,
    delivery.user_id,
    p_created_at
  from private.reminder_deliveries as delivery
  where delivery.id = p_delivery_id
    and delivery.status = 'claimed'
    and delivery.lease_expires_at > p_created_at
  on conflict do nothing;

  return exists (
    select 1
    from private.reminder_unsubscribe_tokens as token
    where token.delivery_id = p_delivery_id
      and token.token_digest = p_token_digest
  );
end;
$$;

revoke execute on function public.store_reminder_unsubscribe_token(
  uuid, bytea, timestamptz
) from public, anon, authenticated;
grant execute on function public.store_reminder_unsubscribe_token(
  uuid, bytea, timestamptz
) to service_role;

create or replace function public.record_reminder_suppression(
  p_user_id uuid,
  p_reason text,
  p_source text,
  p_suppressed_at timestamptz default now()
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if p_reason is null
      or p_source is null
      or p_suppressed_at is null
      or not (
        (p_reason in ('hard_bounce', 'complaint') and p_source = 'provider_webhook')
        or (p_reason = 'manual' and p_source = 'operator')
      ) then
    return false;
  end if;

  return private.apply_reminder_suppression(
    p_user_id,
    p_reason,
    p_source,
    p_suppressed_at
  );
end;
$$;

revoke execute on function public.record_reminder_suppression(
  uuid, text, text, timestamptz
) from public, anon, authenticated;
grant execute on function public.record_reminder_suppression(
  uuid, text, text, timestamptz
) to service_role;

create or replace function public.consume_reminder_unsubscribe_token(
  p_token_digest bytea,
  p_consumed_at timestamptz default now()
)
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_created_at timestamptz;
  v_consumed_at timestamptz;
begin
  if p_token_digest is null
      or octet_length(p_token_digest) <> 32
      or p_consumed_at is null then
    return 'invalid';
  end if;

  select token.user_id, token.created_at, token.consumed_at
  into v_user_id, v_created_at, v_consumed_at
  from private.reminder_unsubscribe_tokens as token
  where token.token_digest = p_token_digest
  for update;

  if not found then
    return 'invalid';
  end if;
  if v_consumed_at is not null then
    return 'already_unsubscribed';
  end if;
  if p_consumed_at < v_created_at then
    return 'invalid';
  end if;

  update private.reminder_unsubscribe_tokens as token
  set consumed_at = p_consumed_at
  where token.token_digest = p_token_digest;

  if not private.apply_reminder_suppression(
    v_user_id,
    'unsubscribed',
    'unsubscribe_token',
    p_consumed_at
  ) then
    raise exception 'reminder_unsubscribe_suppression_failed';
  end if;

  return 'unsubscribed';
end;
$$;

revoke execute on function public.consume_reminder_unsubscribe_token(
  bytea, timestamptz
) from public, anon, authenticated;
grant execute on function public.consume_reminder_unsubscribe_token(
  bytea, timestamptz
) to service_role;
