-- Keep Auth availability evidence aggregate and give operators one fenced,
-- auditable path for serious learner-profile incidents.
create table private.auth_health_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default pg_catalog.now(),
  outcome text not null,
  http_status integer,
  latency_ms integer not null,
  constraint auth_health_checks_outcome_check check (
    outcome in (
      'available',
      'expected_client_error',
      'provider_unavailable',
      'network_error'
    )
  ),
  constraint auth_health_checks_status_check check (
    (outcome = 'available' and http_status between 200 and 299)
    or (
      outcome = 'expected_client_error'
      and http_status between 400 and 499
    )
    or (
      outcome = 'provider_unavailable'
      and http_status between 500 and 599
    )
    or (outcome = 'network_error' and http_status is null)
  ),
  constraint auth_health_checks_latency_check check (
    latency_ms between 0 and 60000
  )
);

comment on table private.auth_health_checks is
  'Aggregate Auth probe outcomes only. It contains no account, profile, request, or response data.';

create index auth_health_checks_checked_at_idx
  on private.auth_health_checks (checked_at desc, id desc);

alter table private.auth_health_checks enable row level security;
revoke all on table private.auth_health_checks
  from public, anon, authenticated, service_role;
revoke all on sequence private.auth_health_checks_id_seq
  from public, anon, authenticated, service_role;

create table private.auth_health_status (
  singleton boolean primary key default true,
  last_checked_at timestamptz,
  last_outcome text,
  last_http_status integer,
  last_latency_ms integer,
  consecutive_provider_failures integer not null default 0,
  alert_state text not null default 'healthy',
  alert_opened_at timestamptz,
  alert_closed_at timestamptz,
  updated_at timestamptz not null default pg_catalog.now(),
  constraint auth_health_status_singleton_check check (singleton),
  constraint auth_health_status_outcome_check check (
    last_outcome is null
    or last_outcome in (
      'available',
      'expected_client_error',
      'provider_unavailable',
      'network_error'
    )
  ),
  constraint auth_health_status_alert_check check (
    alert_state in ('healthy', 'open')
  ),
  constraint auth_health_status_failures_check check (
    consecutive_provider_failures >= 0
  )
);

insert into private.auth_health_status (singleton)
values (true);

comment on table private.auth_health_status is
  'The current aggregate Auth alert state. Three consecutive provider or network failures open the alert.';

alter table private.auth_health_status enable row level security;
revoke all on table private.auth_health_status
  from public, anon, authenticated, service_role;

create table private.learner_profile_operator_recovery_incidents (
  incident_id uuid primary key,
  incident_kind text not null,
  target_user_id uuid not null,
  deployed_commit text not null,
  account_features_rollout text not null,
  learner_profile_lifecycle_enabled boolean not null,
  emergency_accountless_rollback_enabled boolean not null,
  legacy_progress_migration_enabled boolean not null,
  accountless_profile_final_cutover_at timestamptz,
  server_gate_before text not null,
  server_gate_after text not null default 'off',
  session_status text not null,
  status text not null default 'started',
  selected_version_id uuid,
  restore_operation_id uuid,
  restored_version_id uuid,
  removal_status text not null default 'not_started',
  removal_remaining_heads bigint,
  removal_remaining_versions bigint,
  removal_recorded_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint learner_profile_operator_incident_kind_check check (
    incident_kind in ('profile-recovery', 'under-13')
  ),
  constraint learner_profile_operator_incident_commit_check check (
    deployed_commit ~ '^[0-9a-f]{7,64}$'
  ),
  constraint learner_profile_operator_incident_rollout_check check (
    account_features_rollout in ('off', 'internal', 'public')
  ),
  constraint learner_profile_operator_incident_gate_check check (
    server_gate_after = 'off'
  ),
  constraint learner_profile_operator_incident_session_check check (
    session_status in ('unknown', 'valid', 'revoked')
  ),
  constraint learner_profile_operator_incident_status_check check (
    status in (
      'started',
      'locked',
      'guardian_consent_recorded',
      'restored',
      'completed',
      'aborted'
    )
  ),
  constraint learner_profile_operator_incident_removal_status_check check (
    removal_status in ('not_started', 'incomplete', 'completed')
  ),
  constraint learner_profile_operator_incident_removal_counts_check check (
    (removal_remaining_heads is null or removal_remaining_heads >= 0)
    and (removal_remaining_versions is null or removal_remaining_versions >= 0)
  )
);

comment on table private.learner_profile_operator_recovery_incidents is
  'Minimal operator audit records. Runtime gates and sanitized version metadata are retained; profile envelopes are not.';

alter table private.learner_profile_operator_recovery_incidents enable row level security;
revoke all on table private.learner_profile_operator_recovery_incidents
  from public, anon, authenticated, service_role;

create table private.learner_profile_account_locks (
  lock_id uuid primary key,
  incident_id uuid not null,
  user_id uuid not null,
  reason text not null default 'under-13',
  guardian_consent_verified boolean not null default false,
  session_status text not null,
  locked_at timestamptz not null default pg_catalog.now(),
  constraint learner_profile_account_locks_incident_fkey
    foreign key (incident_id)
    references private.learner_profile_operator_recovery_incidents (incident_id),
  constraint learner_profile_account_locks_reason_check check (
    reason = 'under-13'
  ),
  constraint learner_profile_account_locks_session_check check (
    session_status in ('unknown', 'valid', 'revoked')
  ),
  constraint learner_profile_account_locks_unique_target unique (incident_id, user_id)
);

comment on table private.learner_profile_account_locks is
  'Exact-account lock evidence for an under-13 incident. Data removal remains a manual, confirmed operation.';

alter table private.learner_profile_account_locks enable row level security;
revoke all on table private.learner_profile_account_locks
  from public, anon, authenticated, service_role;

create index learner_profile_account_locks_user_idx
  on private.learner_profile_account_locks (user_id);

create or replace function private.record_auth_health_check(
  p_outcome text,
  p_http_status integer,
  p_latency_ms integer
)
returns table (
  outcome text,
  alert_state text,
  alert_action text,
  consecutive_provider_failures integer,
  checked_at timestamptz
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  previous_status private.auth_health_status%rowtype;
  failure_count integer;
  next_alert_state text;
  next_alert_action text := 'none';
  check_time timestamptz := pg_catalog.now();
begin
  if p_outcome not in (
    'available',
    'expected_client_error',
    'provider_unavailable',
    'network_error'
  ) then
    raise exception 'Auth health outcome is invalid' using errcode = '22023';
  end if;
  if p_latency_ms is null or p_latency_ms not between 0 and 60000 then
    raise exception 'Auth health latency is invalid' using errcode = '22023';
  end if;
  if (
    p_outcome = 'network_error' and p_http_status is not null
  ) or (
    p_outcome = 'available'
    and (p_http_status is null or p_http_status not between 200 and 299)
  ) or (
    p_outcome = 'expected_client_error'
    and (p_http_status is null or p_http_status not between 400 and 499)
  ) or (
    p_outcome = 'provider_unavailable'
    and (p_http_status is null or p_http_status not between 500 and 599)
  ) then
    raise exception 'Auth health status does not match outcome'
      using errcode = '22023';
  end if;

  select value.* into strict previous_status
  from private.auth_health_status as value
  where value.singleton
  for update;

  failure_count := case
    when p_outcome in ('provider_unavailable', 'network_error')
      then previous_status.consecutive_provider_failures + 1
    else 0
  end;
  next_alert_state := case when failure_count >= 3 then 'open' else 'healthy' end;
  if next_alert_state = 'open' and previous_status.alert_state <> 'open' then
    next_alert_action := 'open';
  elsif next_alert_state = 'healthy' and previous_status.alert_state = 'open' then
    next_alert_action := 'close';
  end if;

  insert into private.auth_health_checks (
    checked_at,
    outcome,
    http_status,
    latency_ms
  ) values (
    check_time,
    p_outcome,
    p_http_status,
    p_latency_ms
  );

  delete from private.auth_health_checks as old_check
  where old_check.checked_at < check_time - interval '35 days';

  update private.auth_health_status as value
  set last_checked_at = check_time,
      last_outcome = p_outcome,
      last_http_status = p_http_status,
      last_latency_ms = p_latency_ms,
      consecutive_provider_failures = failure_count,
      alert_state = next_alert_state,
      alert_opened_at = case
        when next_alert_action = 'open' then check_time
        else value.alert_opened_at
      end,
      alert_closed_at = case
        when next_alert_action = 'close' then check_time
        else value.alert_closed_at
      end,
      updated_at = check_time
  where value.singleton;

  return query select
    p_outcome,
    next_alert_state,
    next_alert_action,
    failure_count,
    check_time;
end;
$$;

revoke execute on function private.record_auth_health_check(text, integer, integer)
  from public, anon, authenticated, service_role;
grant execute on function private.record_auth_health_check(text, integer, integer)
  to service_role;

create or replace function private.auth_health_report()
returns table (
  last_checked_at timestamptz,
  last_outcome text,
  last_http_status integer,
  last_latency_ms integer,
  consecutive_provider_failures integer,
  alert_state text,
  alert_opened_at timestamptz,
  alert_closed_at timestamptz,
  stale boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    value.last_checked_at,
    value.last_outcome,
    value.last_http_status,
    value.last_latency_ms,
    value.consecutive_provider_failures,
    value.alert_state,
    value.alert_opened_at,
    value.alert_closed_at,
    value.last_checked_at is null
      or value.last_checked_at < pg_catalog.now() - interval '10 minutes'
  from private.auth_health_status as value
  where value.singleton;
$$;

revoke execute on function private.auth_health_report()
  from public, anon, authenticated, service_role;
grant execute on function private.auth_health_report()
  to service_role;

create or replace function private.begin_learner_profile_recovery(
  p_incident_id uuid,
  p_incident_kind text,
  p_target_user_id uuid,
  p_target_confirmation text,
  p_deployed_commit text,
  p_account_features_rollout text,
  p_learner_profile_lifecycle_enabled boolean,
  p_emergency_accountless_rollback_enabled boolean,
  p_legacy_progress_migration_enabled boolean,
  p_accountless_profile_final_cutover_at timestamptz,
  p_session_status text
)
returns table (
  status text,
  incident_id uuid,
  target_user_id uuid,
  server_gate_before text,
  server_gate_after text,
  deployed_commit text,
  started_at timestamptz
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  existing_incident private.learner_profile_operator_recovery_incidents%rowtype;
  access_control private.learner_profile_access_control%rowtype;
  started_at timestamptz := pg_catalog.now();
begin
  if p_incident_id is null
    or p_incident_kind not in ('profile-recovery', 'under-13')
    or p_target_user_id is null
    or p_deployed_commit is null
    or p_deployed_commit !~ '^[0-9a-f]{7,64}$'
    or p_account_features_rollout not in ('off', 'internal', 'public')
    or p_learner_profile_lifecycle_enabled is null
    or p_emergency_accountless_rollback_enabled is null
    or p_legacy_progress_migration_enabled is null
    or p_session_status not in ('unknown', 'valid', 'revoked')
  then
    raise exception 'Recovery incident metadata is invalid' using errcode = '22023';
  end if;
  if (
    p_incident_kind = 'profile-recovery'
    and p_target_confirmation is distinct from 'RECOVER ' || p_target_user_id::text
  ) or (
    p_incident_kind = 'under-13'
    and p_target_confirmation is distinct from 'UNDER-13 ' || p_target_user_id::text
  ) then
    raise exception 'Recovery target confirmation is invalid' using errcode = '22023';
  end if;
  perform 1
  from auth.users as account
  where account.id = p_target_user_id;
  if not found then
    raise exception 'Recovery target account does not exist' using errcode = '22023';
  end if;

  select value.* into existing_incident
  from private.learner_profile_operator_recovery_incidents as value
  where value.incident_id = p_incident_id;
  if found then
    if existing_incident.target_user_id is distinct from p_target_user_id
      or existing_incident.incident_kind is distinct from p_incident_kind
      or existing_incident.deployed_commit is distinct from p_deployed_commit
      or existing_incident.account_features_rollout is distinct from p_account_features_rollout
      or existing_incident.learner_profile_lifecycle_enabled is distinct from p_learner_profile_lifecycle_enabled
      or existing_incident.emergency_accountless_rollback_enabled is distinct from p_emergency_accountless_rollback_enabled
      or existing_incident.legacy_progress_migration_enabled is distinct from p_legacy_progress_migration_enabled
      or existing_incident.accountless_profile_final_cutover_at is distinct from p_accountless_profile_final_cutover_at
      or existing_incident.session_status is distinct from p_session_status
    then
      raise exception 'Recovery incident identity was reused'
        using errcode = '22023';
    end if;
    select value.* into strict access_control
    from private.learner_profile_access_control as value
    where value.singleton
    for update;
    if access_control.rollout_state <> 'off' or access_control.developer_user_id is not null then
      update private.learner_profile_access_control as value
      set rollout_state = 'off',
          developer_user_id = null,
          updated_at = started_at
      where value.singleton;
    end if;
    return query select
      'already_started'::text,
      existing_incident.incident_id,
      existing_incident.target_user_id,
      existing_incident.server_gate_before,
      existing_incident.server_gate_after,
      existing_incident.deployed_commit,
      existing_incident.created_at;
    return;
  end if;

  select value.* into strict access_control
  from private.learner_profile_access_control as value
  where value.singleton
  for update;

  update private.learner_profile_access_control as value
  set rollout_state = 'off',
      developer_user_id = null,
      updated_at = started_at
  where value.singleton;

  insert into private.learner_profile_operator_recovery_incidents (
    incident_id,
    incident_kind,
    target_user_id,
    deployed_commit,
    account_features_rollout,
    learner_profile_lifecycle_enabled,
    emergency_accountless_rollback_enabled,
    legacy_progress_migration_enabled,
    accountless_profile_final_cutover_at,
    server_gate_before,
    server_gate_after,
    session_status,
    created_at,
    updated_at
  ) values (
    p_incident_id,
    p_incident_kind,
    p_target_user_id,
    p_deployed_commit,
    p_account_features_rollout,
    p_learner_profile_lifecycle_enabled,
    p_emergency_accountless_rollback_enabled,
    p_legacy_progress_migration_enabled,
    p_accountless_profile_final_cutover_at,
    access_control.rollout_state,
    'off',
    p_session_status,
    started_at,
    started_at
  );

  return query select
    'started'::text,
    p_incident_id,
    p_target_user_id,
    access_control.rollout_state,
    'off'::text,
    p_deployed_commit,
    started_at;
end;
$$;

revoke execute on function private.begin_learner_profile_recovery(
  uuid, text, uuid, text, text, text, boolean, boolean, boolean, timestamptz, text
) from public, anon, authenticated, service_role;
grant execute on function private.begin_learner_profile_recovery(
  uuid, text, uuid, text, text, text, boolean, boolean, boolean, timestamptz, text
) to service_role;

create or replace function private.list_learner_profile_operator_candidates(
  p_incident_id uuid
)
returns table (
  version_id uuid,
  profile_id uuid,
  generation bigint,
  revision bigint,
  payload_sha256 text,
  payload_bytes integer,
  created_at timestamptz,
  is_current boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    version.id,
    version.profile_id,
    version.generation,
    version.revision,
    version.payload_sha256,
    version.payload_bytes,
    version.created_at,
    head.current_version_id = version.id
  from private.learner_profile_operator_recovery_incidents as incident
  join public.learner_profile_versions as version
    on version.user_id = incident.target_user_id
  left join public.learner_profile_heads as head
    on head.user_id = version.user_id
  where incident.incident_id = p_incident_id
    and incident.incident_kind = 'profile-recovery'
    and incident.status = 'started'
    and incident.server_gate_after = 'off'
    and exists (
      select 1
      from private.learner_profile_access_control as access_control
      where access_control.singleton
        and access_control.rollout_state = 'off'
    )
  order by (head.current_version_id = version.id) desc,
    version.created_at desc,
    version.id desc;
$$;

revoke execute on function private.list_learner_profile_operator_candidates(uuid)
  from public, anon, authenticated, service_role;
grant execute on function private.list_learner_profile_operator_candidates(uuid)
  to service_role;

alter table private.learner_profile_recoveries
  drop constraint learner_profile_recoveries_source_check;
alter table private.learner_profile_recoveries
  add constraint learner_profile_recoveries_source_check check (
    (source = 'local' and source_candidate_id is null)
    or (source = 'protected' and source_candidate_id is not null)
    or (source = 'operator' and source_candidate_id is null)
  );

create or replace function private.restore_learner_profile_from_operator_candidate(
  p_incident_id uuid,
  p_operation_id uuid,
  p_version_id uuid,
  p_candidate_confirmation text
)
returns table (
  status text,
  incident_id uuid,
  target_user_id uuid,
  source_version_id uuid,
  restored_version_id uuid,
  profile_id uuid,
  generation bigint,
  revision bigint,
  payload_sha256 text,
  payload_bytes integer,
  restored_at timestamptz,
  displaced_version_id uuid,
  protected_until timestamptz
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  incident private.learner_profile_operator_recovery_incidents%rowtype;
  candidate public.learner_profile_versions%rowtype;
  current_head public.learner_profile_heads%rowtype;
  previous_version public.learner_profile_versions%rowtype;
  new_version_id uuid;
  next_revision bigint;
  restored_at timestamptz := pg_catalog.now();
  protection_deadline timestamptz;
  request_digest text;
begin
  if p_incident_id is null or p_operation_id is null or p_version_id is null then
    raise exception 'Operator restore identity is invalid' using errcode = '22023';
  end if;

  select value.* into strict incident
  from private.learner_profile_operator_recovery_incidents as value
  where value.incident_id = p_incident_id
  for update;
  if incident.incident_kind <> 'profile-recovery'
    or incident.server_gate_after <> 'off'
  then
    raise exception 'Operator profile recovery is not available'
      using errcode = '42501';
  end if;
  if not exists (
    select 1
    from private.learner_profile_access_control as access_control
    where access_control.singleton
      and access_control.rollout_state = 'off'
  ) then
    raise exception 'Operator profile recovery requires the server gate to be off'
      using errcode = '42501';
  end if;
  if p_candidate_confirmation is distinct from 'RESTORE ' || p_version_id::text then
    raise exception 'Recovery candidate confirmation is invalid'
      using errcode = '22023';
  end if;
  if incident.status = 'restored' then
    if incident.restore_operation_id <> p_operation_id then
      raise exception 'Recovery incident was already restored'
        using errcode = '22023';
    end if;
    return query
    select
      'already_restored'::text,
      incident.incident_id,
      incident.target_user_id,
      version.id,
      incident.restored_version_id,
      version.profile_id,
      version.generation,
      version.revision,
      version.payload_sha256,
      version.payload_bytes,
      version.created_at,
      recovery.displaced_version_id,
      recovery.protected_until
    from public.learner_profile_versions as version
    join private.learner_profile_recoveries as recovery
      on recovery.restored_version_id = version.id
     and recovery.user_id = version.user_id
    where version.id = incident.restored_version_id
      and recovery.operation_id = p_operation_id;
    return;
  end if;
  if incident.status <> 'started' then
    raise exception 'Recovery incident is not open' using errcode = '42501';
  end if;

  select version.* into strict candidate
  from public.learner_profile_versions as version
  where version.id = p_version_id
    and version.user_id = incident.target_user_id;
  perform private.assert_learner_profile_envelope(candidate.envelope);
  if candidate.payload_sha256 is distinct from candidate.envelope #>> '{integrity,payloadSha256}'
    or candidate.payload_bytes is distinct from (candidate.envelope #>> '{integrity,byteLength}')::integer
  then
    raise exception 'Operator recovery candidate metadata is invalid'
      using errcode = '22023';
  end if;

  select head.* into current_head
  from public.learner_profile_heads as head
  where head.user_id = incident.target_user_id
  for update;

  select coalesce(max(version.revision), 0) + 1
  into next_revision
  from public.learner_profile_versions as version
  where version.user_id = incident.target_user_id
    and version.profile_id = candidate.profile_id
    and version.generation = candidate.generation;
  if next_revision <= candidate.revision then
    next_revision := candidate.revision + 1;
  end if;

  request_digest := pg_catalog.rtrim(pg_catalog.translate(
    pg_catalog.encode(
      extensions.digest(
        pg_catalog.convert_to(
          private.canonical_jsonb_text(pg_catalog.jsonb_build_object(
            'candidateVersionId', p_version_id,
            'incidentId', p_incident_id,
            'operationId', p_operation_id,
            'ownerId', incident.target_user_id
          )),
          'UTF8'
        ),
        'sha256'
      ),
      'base64'
    ),
    '+/',
    '-_'
  ), '=');
  new_version_id := extensions.gen_random_uuid();
  protection_deadline := restored_at + interval '30 days';

  insert into public.learner_profile_versions (
    id,
    user_id,
    profile_id,
    generation,
    revision,
    base_revision,
    envelope,
    payload_sha256,
    payload_bytes
  ) values (
    new_version_id,
    incident.target_user_id,
    candidate.profile_id,
    candidate.generation,
    next_revision,
    next_revision - 1,
    candidate.envelope,
    candidate.payload_sha256,
    candidate.payload_bytes
  );

  insert into private.learner_profile_recoveries (
    user_id,
    operation_id,
    request_sha256,
    source,
    source_candidate_id,
    source_profile_id,
    source_generation,
    source_revision,
    restored_profile_id,
    restored_generation,
    restored_revision,
    restored_version_id,
    displaced_profile_id,
    displaced_generation,
    displaced_revision,
    displaced_version_id,
    restored_at,
    protected_until
  ) values (
    incident.target_user_id,
    p_operation_id,
    request_digest,
    'operator',
    null,
    candidate.profile_id,
    candidate.generation,
    candidate.revision,
    candidate.profile_id,
    candidate.generation,
    next_revision,
    new_version_id,
    current_head.profile_id,
    current_head.generation,
    current_head.revision,
    current_head.current_version_id,
    restored_at,
    protection_deadline
  );

  if current_head.user_id is null then
    insert into public.learner_profile_heads (
      user_id,
      profile_id,
      generation,
      revision,
      current_version_id,
      created_at,
      updated_at
    ) values (
      incident.target_user_id,
      candidate.profile_id,
      candidate.generation,
      next_revision,
      new_version_id,
      restored_at,
      restored_at
    );
  else
    update public.learner_profile_heads as head
    set profile_id = candidate.profile_id,
        generation = candidate.generation,
        revision = next_revision,
        current_version_id = new_version_id,
        updated_at = restored_at
    where head.user_id = incident.target_user_id
      and head.current_version_id = current_head.current_version_id;
    if not found then
      raise exception 'Learner profile head changed during operator recovery'
        using errcode = '40001';
    end if;
  end if;

  update private.learner_profile_operator_recovery_incidents as value
  set status = 'restored',
      selected_version_id = p_version_id,
      restore_operation_id = p_operation_id,
      restored_version_id = new_version_id,
      updated_at = restored_at
  where value.incident_id = p_incident_id;

  return query select
    'restored'::text,
    p_incident_id,
    incident.target_user_id,
    p_version_id,
    new_version_id,
    candidate.profile_id,
    candidate.generation,
    next_revision,
    candidate.payload_sha256,
    candidate.payload_bytes,
    restored_at,
    current_head.current_version_id,
    protection_deadline;
end;
$$;

revoke execute on function private.restore_learner_profile_from_operator_candidate(
  uuid, uuid, uuid, text
) from public, anon, authenticated, service_role;
grant execute on function private.restore_learner_profile_from_operator_candidate(
  uuid, uuid, uuid, text
) to service_role;

create or replace function private.record_under_13_account_lock(
  p_incident_id uuid,
  p_target_confirmation text,
  p_guardian_consent_verified boolean,
  p_session_status text
)
returns table (
  status text,
  manual_removal_required boolean,
  session_status text
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  incident private.learner_profile_operator_recovery_incidents%rowtype;
  lock_id uuid;
begin
  if p_incident_id is null
    or p_guardian_consent_verified is null
    or p_session_status not in ('unknown', 'valid', 'revoked')
  then
    raise exception 'Under-13 incident metadata is invalid' using errcode = '22023';
  end if;
  select value.* into strict incident
  from private.learner_profile_operator_recovery_incidents as value
  where value.incident_id = p_incident_id
  for update;
  if incident.incident_kind <> 'under-13'
    or incident.server_gate_after <> 'off'
  then
    raise exception 'Under-13 lock is not available' using errcode = '42501';
  end if;
  if p_target_confirmation is distinct from 'UNDER-13 ' || incident.target_user_id::text then
    raise exception 'Under-13 target confirmation is invalid'
      using errcode = '22023';
  end if;
  if incident.status in ('completed', 'aborted') then
    raise exception 'Under-13 incident is closed' using errcode = '42501';
  end if;
  if incident.status = 'guardian_consent_recorded'
    and not p_guardian_consent_verified
  then
    raise exception 'Verified guardian consent cannot be reversed'
      using errcode = '22023';
  end if;
  if not exists (
    select 1
    from private.learner_profile_access_control as access_control
    where access_control.singleton
      and access_control.rollout_state = 'off'
  ) then
    raise exception 'Under-13 lock requires the server gate to be off'
      using errcode = '42501';
  end if;
  update private.learner_profile_operator_recovery_incidents as value
  set status = case
        when p_guardian_consent_verified then 'guardian_consent_recorded'
        else 'locked'
      end,
      session_status = p_session_status,
      updated_at = pg_catalog.now()
  where value.incident_id = p_incident_id;

  if p_guardian_consent_verified then
    update private.learner_profile_account_locks as lock_record
    set guardian_consent_verified = true,
        session_status = p_session_status
    where lock_record.incident_id = p_incident_id
      and lock_record.user_id = incident.target_user_id;
    return query select
      'guardian_consent_recorded'::text,
      false,
      p_session_status;
    return;
  end if;

  lock_id := extensions.gen_random_uuid();
  insert into private.learner_profile_account_locks (
    lock_id,
    incident_id,
    user_id,
    guardian_consent_verified,
    session_status
  ) values (
    lock_id,
    p_incident_id,
    incident.target_user_id,
    false,
    p_session_status
  )
  on conflict (incident_id, user_id) do update
  set guardian_consent_verified = excluded.guardian_consent_verified,
      session_status = excluded.session_status,
      locked_at = pg_catalog.now();

  return query select
    'locked'::text,
    true,
    p_session_status;
end;
$$;

revoke execute on function private.record_under_13_account_lock(uuid, text, boolean, text)
  from public, anon, authenticated, service_role;
grant execute on function private.record_under_13_account_lock(uuid, text, boolean, text)
  to service_role;

create or replace function private.record_under_13_profile_removal(
  p_incident_id uuid,
  p_target_confirmation text,
  p_session_status text,
  p_remaining_heads bigint,
  p_remaining_versions bigint
)
returns table (
  status text,
  removal_status text,
  session_status text,
  remaining_heads bigint,
  remaining_versions bigint
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  incident private.learner_profile_operator_recovery_incidents%rowtype;
  next_status text;
  recorded_at timestamptz := pg_catalog.now();
begin
  if p_incident_id is null
    or p_session_status not in ('unknown', 'valid', 'revoked')
    or p_remaining_heads is null
    or p_remaining_heads < 0
    or p_remaining_versions is null
    or p_remaining_versions < 0
  then
    raise exception 'Under-13 removal metadata is invalid' using errcode = '22023';
  end if;

  select value.* into strict incident
  from private.learner_profile_operator_recovery_incidents as value
  where value.incident_id = p_incident_id
  for update;
  if incident.incident_kind <> 'under-13'
    or incident.server_gate_after <> 'off'
    or incident.status not in ('locked', 'completed')
  then
    raise exception 'Under-13 removal is not available' using errcode = '42501';
  end if;
  if incident.status = 'completed'
    and (p_remaining_heads <> 0 or p_remaining_versions <> 0)
  then
    raise exception 'Under-13 removal was already completed' using errcode = '22023';
  end if;
  if not exists (
    select 1
    from private.learner_profile_access_control as access_control
    where access_control.singleton
      and access_control.rollout_state = 'off'
  ) then
    raise exception 'Under-13 removal requires the server gate to be off'
      using errcode = '42501';
  end if;
  if p_target_confirmation is distinct from 'UNDER-13 ' || incident.target_user_id::text then
    raise exception 'Under-13 target confirmation is invalid'
      using errcode = '22023';
  end if;

  next_status := case
    when p_remaining_heads = 0 and p_remaining_versions = 0 then 'completed'
    else 'incomplete'
  end;
  update private.learner_profile_operator_recovery_incidents as value
  set status = case when next_status = 'completed' then 'completed' else 'locked' end,
      removal_status = next_status,
      removal_remaining_heads = p_remaining_heads,
      removal_remaining_versions = p_remaining_versions,
      removal_recorded_at = recorded_at,
      session_status = p_session_status,
      updated_at = recorded_at
  where value.incident_id = p_incident_id;

  return query select
    next_status,
    next_status,
    p_session_status,
    p_remaining_heads,
    p_remaining_versions;
end;
$$;

revoke execute on function private.record_under_13_profile_removal(uuid, text, text, bigint, bigint)
  from public, anon, authenticated, service_role;
grant execute on function private.record_under_13_profile_removal(uuid, text, text, bigint, bigint)
  to service_role;

create or replace function private.learner_profile_account_is_locked(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from private.learner_profile_account_locks as lock_record
    where lock_record.user_id = p_user_id
      and not lock_record.guardian_consent_verified
  );
$$;

revoke execute on function private.learner_profile_account_is_locked(uuid)
  from public, anon, authenticated, service_role;
grant execute on function private.learner_profile_account_is_locked(uuid)
  to authenticated;

drop policy if exists "Users can view their own learner profile head"
  on public.learner_profile_heads;
create policy "Users can view their own learner profile head"
  on public.learner_profile_heads
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    and not private.learner_profile_account_is_locked(user_id)
  );

drop policy if exists "Users can view their own learner profile versions"
  on public.learner_profile_versions;
create policy "Users can view their own learner profile versions"
  on public.learner_profile_versions
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    and not private.learner_profile_account_is_locked(user_id)
  );

create or replace function private.reject_locked_learner_profile_head_write()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if private.learner_profile_account_is_locked(new.user_id) then
    raise exception 'Learner profile account is locked'
      using errcode = '42501';
  end if;
  return new;
end;
$$;

revoke execute on function private.reject_locked_learner_profile_head_write()
  from public, anon, authenticated, service_role;

drop trigger if exists reject_locked_learner_profile_head_write
  on public.learner_profile_heads;
create trigger reject_locked_learner_profile_head_write
before insert or update on public.learner_profile_heads
for each row
execute function private.reject_locked_learner_profile_head_write();

comment on function private.restore_learner_profile_from_operator_candidate(
  uuid, uuid, uuid, text
) is
  'Restores a confirmed sanitized candidate as a new protected revision and records the displaced head. It never patches a head or removes a receipt.';
