import{spawn,execFileSync}from'node:child_process';import{createServer}from'node:http';import{readFile,writeFile,mkdir}from'node:fs/promises';import{resolve,extname}from'node:path';import{chromium}from'playwright';
const out=resolve('.cache/tiny-swords-perf');const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://local').pathname;let body=p==='/'?Buffer.from('<!doctype html><title>Disposable Tiny Swords background benchmark</title><style>body{margin:0}iframe{width:1054px;height:454px;border:0}</style><iframe class="tiny-swords-frame" src="/tiny-swords-xp-game/index.html"></iframe>'):await readFile(resolve('_site','.'+p));if(p==='/tiny-swords-xp-game/index.html')body=Buffer.from(body.toString().replace('</head>',"<script>window.addEventListener('DOMContentLoaded',()=>{window.edeniaStudySession=1;window.edeniaStudyLevel=1;window.edeniaStudyLayout=null;window.edeniaStudyReady=true})</script></head>"));if(p.endsWith('.js'))body=Buffer.from(body.toString().replaceAll('8037','8048'));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.css':'text/css'})[extname(p)]||(p==='/'?'text/html':'application/octet-stream'));res.end(body)}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(8048,'127.0.0.1',r));
const child=spawn(chromium.executablePath(),['--remote-debugging-port=9448','--user-data-dir='+out+'/normal-profile','--no-first-run','--no-default-browser-check','about:blank'],{stdio:'ignore'});for(let i=0;i<60;i++){try{await fetch('http://127.0.0.1:9448/json/version');break}catch{await new Promise(r=>setTimeout(r,1000))}}
async function connect(){const info=await(await fetch('http://127.0.0.1:9448/json/version')).json();const ws=new WebSocket(info.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const [r,j]=pending.get(m.id)||[];pending.delete(m.id);m.error?j?.(m.error):r?.(m.result)}};return {ws,send:(method,params={},sessionId)=>new Promise((r,j)=>{const n=++id;pending.set(n,[r,j]);ws.send(JSON.stringify({id:n,method,params,...(sessionId?{sessionId}:{})}))})}}
let c;
async function evalJS(session,expression){const r=await c.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true},session);if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value}
async function attach(target){return(await c.send('Target.attachToTarget',{targetId:target,flatten:true})).sessionId}
function cpu(pids){return pids.map(p=>{try{const raw=execFileSync('ps',['-p',String(p.id),'-o','time=,rss=']).toString().trim().split(/\s+/);const parts=raw[0].split(':').map(Number);return {id:p.id,type:p.type,time:parts.reduce((n,v)=>n*60+v,0),rssKiB:Number(raw[1])}}catch{return {...p,time:null}}})}
async function sample(label,pids){const a=cpu(pids),start=Date.now();await new Promise(r=>setTimeout(r,15000));const b=cpu(pids);const secs=(Date.now()-start)/1000;return {label,seconds:secs,processes:b.map(p=>({...p,cpuPercent:p.time===null?null:Math.max(0,100*(p.time-a.find(x=>x.id===p.id).time)/secs)}))}}
const results=[];
try{
 c=await connect();const list=await c.send('Target.getTargets');const target=(await c.send('Target.createTarget',{url:'about:blank'})).targetId;let session=await attach(target);await c.send('Page.enable',{},session);await c.send('Page.navigate',{url:'http://127.0.0.1:8048/?init'},session);await new Promise(r=>setTimeout(r,7000));
for(let i=0;i<90;i++){const state=await evalJS(session,'({ready:document.querySelector(".tiny-swords-frame")?.contentWindow.edeniaGameLevel,frame:document.querySelector(".tiny-swords-frame")?.src,status:document.querySelector(".tiny-swords-frame")?.contentDocument?.body.innerText.slice(0,200)})');if(state.ready){console.log('GAME_READY',state);break;}if(i===89)throw new Error('Game not ready '+JSON.stringify(state)+' '+await evalJS(session,'document.body.innerHTML.slice(0,300)'));await new Promise(r=>setTimeout(r,1000));}
 await new Promise(r=>setTimeout(r,6000));
 await evalJS(session,`(()=>{window.__vis=[{state:document.visibilityState,t:performance.now()}];document.addEventListener('visibilitychange',()=>__vis.push({state:document.visibilityState,t:performance.now()}));window.__raf=0;const tick=()=>{__raf++;requestAnimationFrame(tick)};tick();return true})()`);
 await c.send('Page.bringToFront',{},session);const pids=(await c.send('SystemInfo.getProcessInfo')).processInfo.filter(p=>['renderer','GPU','browser'].includes(p.type)).map(({id,type})=>({id,type}));await c.send('Target.detachFromTarget',{sessionId:session});c.ws.close();
 results.push(await sample('foreground-detached',pids));
 c=await connect();session=await attach(target);const before=await evalJS(session,'({visibility:document.visibilityState,events:__vis,raf:__raf,game:document.querySelector(".tiny-swords-frame")?.contentWindow.edeniaGameLevel})');const blank=(await c.send('Target.createTarget',{url:'about:blank'})).targetId;const bs=await attach(blank);await c.send('Page.bringToFront',{},bs);await c.send('Target.detachFromTarget',{sessionId:bs});await c.send('Target.detachFromTarget',{sessionId:session});c.ws.close();
 results.push(await sample('background-detached',pids));
 c=await connect();session=await attach(target);const after=await evalJS(session,'({visibility:document.visibilityState,events:__vis,raf:__raf,game:document.querySelector(".tiny-swords-frame")?.contentWindow.edeniaGameLevel})');await writeFile(out+'/background.json',JSON.stringify({before,after,results},null,2));console.log({before,after,results});
}finally{c?.ws.close();child.kill('SIGTERM');server.close()}
